### ISSUE TITLE
split op questions for model otimizer

### ISSUE THREAD

**Issue by kaixuanliu** [opencv/dldt#1]
Hi, I ran across a problem when I use mo to convert a caffemodel, it shows `'LayerParameter' object has no attribute 'num_split'` for split layer. However, as far as I am concerned, split layer in caffe is just a copy operation. So I think this sentence `_out_shape[node.axis] = np.int64(input_node.shape[node.axis] / _node.pb.num_split)` in `mo/ops/split.py` should be like this:
`out_shape[node.axis] = np.int64(input_node.shape[node.axis])`
You may mistake split layer as slice layer, I guess.

**Comment by meshaun9** [comment]
Hi @kaixuanliu, It seems that you may be right based of what's currently implemented and what's in caffe's documentation for the split layer. I will do a test with the split layer coded as a copy instead of needing num_split value and check the results.

**Comment by lazarevevgeny** [comment]
Hi @kaixuanliu. It is not enough just to change the infer function for the Split layer. In fact, if you do this you break conversion of the models from other frameworks (TF, MXNet, Kaldi, etc). The right solution would be to eliminate Split layers during conversion of the Caffe models. Create a file "model_optimizer/extensions/front/caffe/remove_split.py" with the following content:

```python
from mo.front.common.replacement import FrontReplacementOp

class RemoveSplit(FrontReplacementOp):
    op = "Split"
    enabled = True
    def replace_sub_graph(self, graph, match):
        split = match['op']
        split.op = 'Identity'
        for _, __, edge_attrs in graph.out_edges(split.id, data=True):
            edge_attrs['out'] = 0
```

**Comment by kaixuanliu** [comment]
Hi,@lazarevevgeny I agree with you. Sorry I am not familiar with TF or MXNet, and I have this concern before as you.
