### ISSUE TITLE
Is there API for C++？

### ISSUE THREAD

**Issue by LuWei6896** [opencv/dldt#101]
@shubha-ramani hai,my master!
i wnna to use c++ API ，there is Python* API only.Could you give me a link?
![2019-03-11 17-28-54屏幕截图](https://user-images.githubusercontent.com/32614962/54113970-58276900-4424-11e9-8ec9-e321bc50a074.png)

**Comment by alalek** [comment]
Like [this](http://docs.openvinotoolkit.org/R5/classInferenceEngine_1_1CNNNetwork.html)?

**Comment by LuWei6896** [comment]
@alalek fine,thanks!
