### ISSUE TITLE
Intel(R) HD Graphics 4400 supported

### ISSUE THREAD

**Issue by kaynon17** [opencv/dldt#106]
My machine:
Intel(R) Core(TM) i3-4170 CPU @ 3.70GHz
Intel(R) HD Graphics 4400

When I used this engine with -d GPU,  I got an error:
No OpenCL device found which would match provided configuration:
   Intel(R) HD Graphics 4400: missing out of order support
   Intel(R) Core(TM) i3-4170 CPU @ 3.70GHz: invalid device type

Did this mean that this engine did not support Intel(R) HD Graphics 4400 ?

Thanks

**Comment by shubha-ramani** [comment]
Dear Kanyon17:

As the following forum answer says 

> Intel OpenVINO toolkit and Deep Learning Deployment Inference Engine target the same class of devices as The Intel Compute Runtime OpenCL implementation ("NEO").
> 

The following  Intel Developer Zone forum link explains it in detail:
[https://software.intel.com/en-us/forums/opencl/topic/779709](https://software.intel.com/en-us/forums/opencl/topic/779709)

The short answer is if you're getting that error "missing out of order support" OpenVino won't run on it.

Hope it helps !

Thanks,

Shubha

**Comment by kaynon17** [comment]
I found in this page https://github.com/intel/compute-runtime/blob/master/README.md.
The Supported Platforms : 
1、Intel Core Processors with Gen8 graphics devices (formerly Broadwell) - OpenCL 2.1
2、Intel Core Processors with Gen9 graphics devices (formerly Skylake, Kaby Lake, Coffee Lake) - OpenCL 2.1
3、Intel Atom Processors with Gen9 graphics devices (formerly Apollo Lake, Gemini Lake) - OpenCL 1.2
But Intel(R) HD Graphics 4400 is Gen7 graphics device

Thanks, It helps me a lot!  I will close this issue

Kaynon17
