### ISSUE TITLE
Is it possible to replace SoftPlus with supported ops?

### ISSUE THREAD

**Issue by heagoo** [opencv/dldt#111]
In the document, there is an example of SquaredDifference. I want to do similar things for Softplus, but I wonder if exp and log function are already supported?
Tensorflow softplus: log(exp(features) + 1).
Thanks!

**Comment by shubha-ramani** [comment]
Dear @heagoo,

Please refer to the following documentation for supported layers in Inference Engine:
[https://software.intel.com/en-us/articles/OpenVINO-ModelOptimizer](https://software.intel.com/en-us/articles/OpenVINO-ModelOptimizer)
On the side bar, navigate to What You Need to Know About Your Model. Then click to the Supported Layers links for the various network brands (Caffe, Tensorflow, etc...).  I took a quick look at Tensorflow and SoftPlus is not supported.

However you can add a custom layer to support it. I answered a previous forum post on how to do that:
[https://software.intel.com/en-us/forums/computer-vision/topic/805980](https://software.intel.com/en-us/forums/computer-vision/topic/805980)

**Comment by heagoo** [comment]
Thanks, I successfully added a customized layer by writing an extension.
But I still encountered a crash issue (the network is wavenet), and debug shows it is not caused by my code.   Of course, that's another issue.
