### ISSUE TITLE
Unable to infer/propagate shape

### ISSUE THREAD

**Issue by mrinmayk** [opencv/dldt#112]
Hello

On 2018.1.249,

I used a shape input as [1,96,96,3] to avoid -1 shape issue when tying model optimizer but yet get input shape error (similar to https://stackoverflow.com/posts/55420326/ last comment)

Please guide / inform VINO team of issue.

(I also asked this question here - https://stackoverflow.com/posts/55420326/edit)

Mike

**Comment by dkurt** [comment]
> 2018.1.249

Have you tried newer versions? It looks like one year old release.

**Comment by mrinmayk** [comment]
yes, a newer version (R1.2) worked right thereafter; forgot to update thread apologies, close it.
Sent from Yahoo Mail for iPhone


On Saturday, March 30, 2019, 5:45 AM, Dmitry Kurtaev <notifications@github.com> wrote:



2018.1.249


Have you tried newer versions? It looks like one year old release.
