### ISSUE TITLE
where to get 2019 R1

### ISSUE THREAD

**Issue by glorysdj** [opencv/dldt#115]
can not be found here:  https://github.com/opencv/dldt/releases

**Comment by violet17** [comment]
https://software.intel.com/en-us/openvino-toolkit

**Comment by qiyuangong** [comment]
Thanks @violet17 
That link works! But, it only provides installation binaries. Where can we find the source code?

**Comment by banderlog** [comment]
@violet17 besides openVINO binaries.

When it will be released on github?

**Comment by asuhov** [comment]
Hello, we will publish 2019 R1 sources approximately in 2 weeks.

**Comment by banderlog** [comment]
![](https://i.imgur.com/Bz7VjEU.png)

**Comment by asuhov** [comment]
@banderlog  This commit corresponds to R1 release: https://github.com/opencv/dldt/commit/b235c73481a6f133e1d182d91e5e2c29e8a460e5, we will add release tag a bit later.

**Comment by glorysdj** [comment]
> @glorysdj , now release 2019 R1 and 2019 R2 published. Can we close this issue?

yes, thanks.
