### ISSUE TITLE
Is there any format change between OpenVINO R3 and R4?

### ISSUE THREAD

**Issue by chaoli2** [opencv/dldt#127]
I use OpenVINO for object detection in my [project](https://github.com/chaoli2/ros_openvino_toolkit-1/tree/yolov2_support). I convert [yolov2-voc model](https://pjreddie.com/darknet/yolov2/) to [OpenVINO IR](https://drive.google.com/drive/folders/1n5xjVWplQn85yj81j2aZUTIb65yQyEGA?usp=sharing), and it works well under OpenVINO R3. 

However, when I upgrade OpenVINO R3 to R4, I received ```[ ERROR ] Dims and format are inconsistent. ``` I've checked that my code and model files are not changed. And I've spent some time to  locate the root cause but no clue yet. Interface ```CreateInferRequestPtr()``` is the [entrance ](https://github.com/intel/ros_openvino_toolkit/blob/fcf0f9d38cfca40ad3b08150c28e43e5537bc54d/dynamic_vino_lib/src/engines/engine.cpp#L27) in my project which leads to this issue. It is defined in class "[InferenceEngine::ExecutableNetwork ](https://github.com/opencv/dldt/blob/91160e65cf66e7fbc709245a8ba948a4c555e443/inference-engine/include/cpp/ie_executable_network.hpp#L79)".   I also found that this exception is caused [here](https://github.com/opencv/dldt/blob/91160e65cf66e7fbc709245a8ba948a4c555e443/inference-engine/src/inference_engine/ie_layouts.cpp#L248). But I have no idea why. I'd like to know what changes between R3 and R4 will cause this issue and how I could update my project to fix it. Is there anyone can help? Thanks very much.

**Comment by shubha-ramani** [comment]
Dear @chaoli2 

Is there any reason you're using such  an ancient version of OpenVino ? Please upgrade your project to the latest version, 2019 R1.  

Thanks,

Shubha

**Comment by chaoli2** [comment]
@shubha-ramani 
Thanks for your advice. Actually upgrading OpenVINO is exactly what we want to do. This issue blocks the upgrading process. 
 At the beginning, our project was developed under OpenVINO R3, so we first verified that there is no such kind issue at that time. When we tried to upgrade OpenVINO R4, even OpenVINO R5, we received this ```[ ERROR ] Dims and format are inconsistent.``` Currently we have no idea what we can do fix it.

**Comment by chaoli2** [comment]
Is there official sample code for yolov2? I only found yolov3 samples inside the OpenVINO package. I have to refer to community projects, like [this](https://github.com/feng1sun/YOLO-OpenVINO). Sometimes they may be out of date due to lack of maintenance.

**Comment by shubha-ramani** [comment]
Dear @chaoli2 

Unfortunately we do not have yolo v2 samples. We only have yolo v3 (both Python and C++ versions). 
To answer your question about the format change between OpenVino R3 and R4, here is what I suggest. It's a bit laborious but if you follow this method you will likely answer your question.
1) clone the R4 version of dldt
2)  Follow the below doc to build a DEBUG version of Inference Engine 
[https://github.com/opencv/dldt/blob/2018/inference-engine/README.md](https://github.com/opencv/dldt/blob/2018/inference-engine/README.md)
Make sure you build a debug version of your inference app also
3) Step through the code using your favorite debugger

If you follow these steps you will find out the exact layer which is causing that error. I have done this before myself and it's quite effective.

Hope you will give it a try !

Thanks for using OpenVino,

Shubha

**Comment by chaoli2** [comment]
Thanks for your information. I've found the cause for ```[ ERROR ] Dims and format are inconsistent.```

When initializing output ptr, there is no need to ``` output_data_ptr->setLayout(InferenceEngine::Layout::NCHW)``` but I did.

Everything goes well after I remove above code. The only question now is why this error cannot be reproduced under OpenVINO R3.
