### ISSUE TITLE
When will a release tag for R1 be set?

### ISSUE THREAD

**Issue by fkhoshne** [opencv/dldt#135]
Would like a release tag to lock to R1 release without specifying the specific commit id or targeting master.

**Comment by banderlog** [comment]
<https://github.com/opencv/dldt/issues/115#issuecomment-487267649>

**Comment by shubha-ramani** [comment]
@fkhoshne it is done :
[https://github.com/opencv/dldt/tags](https://github.com/opencv/dldt/tags)

**Comment by fkhoshne** [comment]
@shubha-ramani Thank you!
