### ISSUE TITLE
Option 'disable-inlined-alloca-merging' registered more than once

### ISSUE THREAD

**Issue by r0l1** [opencv/dldt#14]
The Inference Engine fails when used together with the OpenCV DNN backend:

```
net.setPreferableBackend(cv::dnn::DNN_BACKEND_INFERENCE_ENGINE);
net.setPreferableTarget(cv::dnn::DNN_TARGET_OPENCL);
```

Runtime error:
```
: CommandLine Error: Option 'disable-inlined-alloca-merging' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options
```

Any hints why this is caused?

**Comment by elvin-nnov** [comment]
What is OpenCV version have you used?

**Comment by r0l1** [comment]
Latest master release.

**Comment by vladimir-paramuzov** [comment]
@r0l1 You probably have 2 different versions of llvm loaded: one comes from OpenCL runtime, one from OpenCV (I suppose you have Halide enabled). So I'd suggest trying OpenCV version without Halide.

**Comment by r0l1** [comment]
@vladimir-paramuzov thanks! that was the case
