### ISSUE TITLE
exp (Exponential) operation not supported by inference engine?

### ISSUE THREAD

**Issue by wuhy08** [opencv/dldt#142]
I tried to load the IR network using inference engine by both python and C++ and get the following error:

C++: 
`[ ERROR ] Error reading network: Unsupported Activation layer type: exp`

Python:
`  File "ie_api.pyx", line 271, in openvino.inference_engine.ie_api.IENetwork.__cinit__
RuntimeError: Error reading network: Unsupported Activation layer type: exp`

After a little investigation I speculate that the error comes from here:

https://github.com/opencv/dldt/blob/b235c73481a6f133e1d182d91e5e2c29e8a460e5/inference-engine/src/inference_engine/ie_cnn_layer_builder.h#L130-L156

It seems to me that "exp" is not a valid activation layer from the code snippet above. 

However, the model was converted from ONNX to IR using model optimizer, and I found that the conversion seems implemented, shown in this file:

https://github.com/opencv/dldt/blob/b235c73481a6f133e1d182d91e5e2c29e8a460e5/model-optimizer/extensions/front/onnx/exp_ext.py#L21-L28

Therefore, I wonder if exponential operation is also implemented in the inference engine.

**Comment by wuhy08** [comment]
It seems that the inference engine has the capability to do `eltwise_exp`, right?

See the following snippet:

https://github.com/opencv/dldt/blob/b235c73481a6f133e1d182d91e5e2c29e8a460e5/inference-engine/src/mkldnn_plugin/nodes/mkldnn_activation_node.cpp#L80-L84

**Comment by wuhy08** [comment]
Here is the xml and bin model I used:

https://wdc.box.com/s/0qqqekuxk2a3g50xrschovwnmu39w21i

**Comment by shubha-ramani** [comment]
Dearest @wuhy08 

This is a known bug. It will be fixed in 2019 R2 - which hopefully should arrive around July/August time frame. No promises though about release dates though !

Shubha

**Comment by wuhy08** [comment]
Thank you, @shubha-ramani .
