### ISSUE TITLE
when i use the Movidius in the ubuntu 16.04, "[ ERROR ] Cannot find plugin to use :"

### ISSUE THREAD

**Issue by xiaoxiaotao** [opencv/dldt#15]
It is my command "./security_barrier_camera_demo -i /media/bozhon/ESD-USB/test5.avi -m /home/bozhon/openvino/open_model_zoo/model_downloader/Security/object_detection/barrier/0106/dldt/vehicle-license-plate-detection-barrier-0106.xml -d MYRIAD"

I do not find the myriad_plugin in the "/home/bozhon/openvino/dldt/inference-engine/src" .

**Comment by moslex** [comment]
Hello, @xiaoxiaotao 
Myriad plugin is not a part of open source distribution yet. Please, read this FAQ: https://01.org/openvinooolkit/faq for more details. 

Please, use Intel(R) distribution of OpenVINO(tm) toolkit to run inference on Myriad: https://software.intel.com/en-us/openvino-toolkit

**Comment by xiaoxiaotao** [comment]
thank you
