### ISSUE TITLE
RuntimeError: AssertionFailed: perm.size() == 4 using inference_engine load function

### ISSUE THREAD

**Issue by wuhy08** [opencv/dldt#152]
Hi,
When I used Python API of inference_engine to load my model, the following error is thrown when `load` is called:

```
Traceback (most recent call last):
  File "/home/wd-ai/git-pkgs/OpenVINO-YoloV3/try_multi_thread.py", line 113, in <module>
    inferencers.append(Inferencer())
  File "/home/wd-ai/git-pkgs/OpenVINO-YoloV3/try_multi_thread.py", line 76, in __init__
    self.exec_net = self.plugin.load(network=self.net, num_requests=num_requests)
  File "ie_api.pyx", line 395, in openvino.inference_engine.ie_api.IEPlugin.load
  File "ie_api.pyx", line 406, in openvino.inference_engine.ie_api.IEPlugin.load
RuntimeError: AssertionFailed: perm.size() == 4
```

The model which throws the error is attached in the following link:
https://wdc.box.com/s/o305d7we1dn2bsr7s3fn87fozm45wemi

What is also attached in the link is a model without the error.

The only difference between two models are the "Permute" operation.

Therefore I suspect there are some problems in the permute operation of inference_engine.

**Comment by shubha-ramani** [comment]
Dear @wuhy08

I have seen  a similar issue before on the Intel Developer Zone OpenVino forums. I have to ask - are you using the latest and greatest 2019 OpenVino release ? Because this issue (if you agree that it's the same one as the [IDZ Issue](https://software.intel.com/en-us/forums/computer-vision/topic/805570) has been fixed.

Please report back here and let us know.

Sorry for the inconvenience and thanks for using OpenVino !

Shubha

**Comment by wuhy08** [comment]
Dear @shubha-ramani 
I think I am using 2nd latest and still greatest OpenVINO 2019R1. I just noticed R1.1 is released. Let me try with that and get back to you. But my issue is a little different from what is on IDZ. The author there wants to permute 3 dims, while I want to permute 5 dims. However, I have a workaround in my model to avoid permutation in 5 dims. 

I also have some other issues with IE. I will investigate it by myself before posting. Hopefully R1.1 will fix it. I will close this one for now.

Thank you so much and have a great weekend!
