### ISSUE TITLE
ImportError: Could not import IENetwork

### ISSUE THREAD

**Issue by karkadad** [opencv/dldt#167]
I followed the build instructions on the dldt Github page: https://github.com/opencv/dldt/blob/2019/inference-engine/README.md for building with OpenMP threading.
This was the cmake  command used:
cmake -DCMAKE_BUILD_TYPE=Release -DTHREADING=OMP ..

When I try to run the inference script, I run into the following error:
Traceback (most recent call last):
      from openvino.inference_engine import IENetwork, IEPlugin
ImportError: cannot import name 'IENetwork' from 'openvino.inference_engine' (unknown location)

I made sure the built inference engine libraries and bin files were in LD_LIBRARY_PATH, PATH, and PYTHONPATH env variables, but still run into this error. This is on a Linux system and using python.
Any help is appreciated!

**Comment by shubha-ramani** [comment]
Dear @karkadad 
Sorry you're having trouble. I will attempt to reproduce your error and report back on this forum.

Thanks,

Shubha

**Comment by kennethMCraft** [comment]
While i am concerned with your unknown location error. Can you tell me if you were able to get a  python sample to run ? 
I built with OpenMP enabled and was able to get openvino running correctly.

**Comment by karkadad** [comment]
I was able to get a python sample to run with the pre-built OpenVINO libraries which I believe is built with TBB by default.
I then tried to build OpenVINO myself with OpenMP and these are the commands I used:
cmake -DCMAKE_BUILD_TYPE=Release -DTHREADING=OMP ..
make -j
I then made sure the built inference engine libraries and bin files were in LD_LIBRARY_PATH, PATH, and PYTHONPATH env variables. I'm not sure if I'm missing any steps here.
But when I then try to run the python sample, it exits with the error :
Traceback (most recent call last):
from openvino.inference_engine import IENetwork, IEPlugin
ImportError: cannot import name 'IENetwork' from 'openvino.inference_engine' (unknown location)

**Comment by KMC-intel** [comment]
Inside of the ie-bridges folder there should a python folder that has some samples. You should be able to run those samples. 
There is also a readme in that folder that shows what directory to add to your pythonpath.

**Comment by KMC-intel** [comment]
also did you build with the -DENABLE_PYTHON flag ?

**Comment by karkadad** [comment]
I had tried both with and without the -DENABLE_PYTHON flag while building with the following commands:
1. cmake -DCMAKE_BUILD_TYPE=Release -DTHREADING=OMP .. 
2. cmake -DCMAKE_BUILD_TYPE=Release -DTHREADING=OMP -DENABLE_PYTHON=ON -DENABLE_MKL_DNN=ON .. 

But I think my issue was that I wasn't adding the right directory to the PYTHONPATH.  Adding <inference-engine-dir>/bin/intel64/Release/lib/python_api/python3.7 to the PYTHONPATH env variable seems to have fixed the issue. Earlier I was only adding <inference-engine-dir>/bin directory to the PYTHONPATH which seems to be the issue?

Thank you @shubha-ramani and @KMC-intel for your help! I will be closing the issue now.
