### ISSUE TITLE
There is no registered "infer" function for node "33" with op = "Floor". Please implement this function in the extensions.

### ISSUE THREAD

**Issue by Aeroxander** [opencv/dldt#174]
So I'm trying to convert an ONNX model to OpenVINO and I first had this error: 
`Original exception message: One/both of widths_scale = None and height_scale = None is not defined for Upsample node 44`
But I just manually set both variables to 1.0 and that seemed to fix this (hope I didn't destroy the network accuracy, have no idea what the actual values would be).

But now that this problem is semi-fixed, I get this error:
`
There is no registered "infer" function for node "33" with op = "Floor". Please implement this function in the extensions.`

Is the only way to fix this to manually add the Floor function myself?

**Comment by shubha-ramani** [comment]
Dearest @Aeroxander 
Hi again ! I believe I have already answered your [IDZ Forum Post](https://software.intel.com/en-us/forums/computer-vision/topic/812225)

You need to create a custom layer for "Floor", and that should solve your problem. 

Thanks for using OpenVino !

Shubha

**Comment by Aeroxander** [comment]
Ah yes I'll close this one now, thanks!
