### ISSUE TITLE
why it will coredump when i compile a libXX.so based on openvino_2019.1.144

### ISSUE THREAD

**Issue by jlygit** [opencv/dldt#177]
hello,
i compile a libXX.so using g++ and wrapping some c api (extern "C") like that,

![image](https://user-images.githubusercontent.com/10195989/59367715-3f09bd80-8d6f-11e9-8ad0-85cb702c4a72.png)

i call the c api in a c project and it works right when i compile library based on openvino_2018.4.420, but it will coreump when  i compile library based on openvino_2019.1.144.

i gdb the coredump file is like that,

![image](https://user-images.githubusercontent.com/10195989/59368047-f56da280-8d6f-11e9-9e82-87b9414b1ce5.png)

why?
the test code like that,

![image](https://user-images.githubusercontent.com/10195989/59367679-2d281a80-8d6f-11e9-91dc-e5c9723a47c1.png)

and all the code and model is as follow,
[openvino_test_code.zip](https://github.com/opencv/dldt/files/3282243/openvino_test_code.zip)

thanks,

**Comment by alalek** [comment]
> gcc-4.8.5

Probably you catched problem with ABI mismatch (it should be compatible with C++11, like OpenVINO compiled).
More info is available via searching for this keyword: `_GLIBCXX_USE_CXX11_ABI`.

**Comment by jlygit** [comment]
@alalek 
hi,
i use g++ 4.8.5,  and the CFLAGS  is like that
CFLAGS = -std=c++11  -fPIC -fPIE -O3 -DHAVE_AVX2 -mavx -mavx2  -D_GLIBCXX_USE_CXX11_ABI=0

but it cannot solve the problem

**Comment by jlygit** [comment]
and all sample from openvino_2019.1.144 are work well.
but it will coredump when i compile a libXX.so based on openvino_2019.1.144.
i don't know why it works when i compile a libXX.so based on openvino_2018.4.420.

**Comment by alalek** [comment]
>  -D_GLIBCXX_USE_CXX11_ABI=0

Try `_GLIBCXX_USE_CXX11_ABI=1` instead (modern GCC 5.x+ assumes that). OpenVINO has been compiled using C++11 compilation mode.

---

Alternatively you can try to build code from sources of this repository

**Comment by jlygit** [comment]
@alalek 
It doesn't solve the problem when i try to build code from sources of this repository.
can you help to complie the test code what i upload and see what happen to it?
the code is as follow,
[openvino2019_test.zip](https://github.com/opencv/dldt/files/3285393/openvino2019_test.zip)

and i complie it like that,
`g++ test.c tveAiContext.cpp tveWrapper.cpp  -std=c++11 -I. -I/opt/intel/openvino/inference_engine/include -L/opt/intel/openvino_2019.1.144/deployment_tools/inference_engine/lib/intel64/ -linference_engine  -ldl -fPIE -g  -o test`

**Comment by jlygit** [comment]
is someone meet this confuse?
