### ISSUE TITLE
clang support

### ISSUE THREAD

**Issue by ngeorgis** [opencv/dldt#18]
Trying to compile inference engine with clang 3.9 and 6.0 , not many issues in general looks good and was able run the samples.

Can we add support for clang?

JFTR one minor issue was:

`/src/OpenVino/dldt/inference-engine/src/hetero_plugin/fallback_policy.cpp:52:11: error: comparison of unsigned expression >= 0 is always true
      [-Werror,-Wtautological-compare]
    if (i >= 0) {
`

Thanks,

Nikos

**Comment by moslex** [comment]
Hello, @ngeorgis 
We do not have clang support in IE for now.
It will be great to get pull request from you to enable it.
