### ISSUE TITLE
Single-threaded inference spawns multiple threads

### ISSUE THREAD

**Issue by gasgallo** [opencv/dldt#185]
I'm using OPENVINO 2019 R1.1 on Ubuntu 18.04.
My CPU has 4 cores.
Statistics on threads are obtained using `top -H -b -n1` command and `grep` on the executable name.

I want my inference to run single-threaded, but built-in parameters seem to have no effect. This is my code:
```
std::map<std::string, std::string> config = {
        {InferenceEngine::PluginConfigParams::KEY_CPU_THREADS_NUM, "1"},
        {InferenceEngine::PluginConfigParams::KEY_CPU_BIND_THREAD, InferenceEngine::PluginConfigParams::YES},
        {InferenceEngine::PluginConfigParams::KEY_CPU_THROUGHPUT_STREAMS, "1"}
        };
InferenceEngine::ExecutableNetwork executable_net = myPlugin.LoadNetwork(myNetwork, config);
```
I tried all the possible combinations of the 3 parameters above but the inference uses 9 or more threads (even though most of the computation is done by one single core).

As explained here [https://docs.openvinotoolkit.org/latest/_docs_optimization_guide_dldt_optimization_guide.html](url):
```
Since R1 2019, the OpenVINO™ toolkit comes pre-compiled with Intel TBB,
so any OpenMP* API or environment settings (like OMP_NUM_THREADS)
has no effect anymore. Certain tweaks like number of threads used for
inference on the CPU) are still possible via CPU configuration options.
```
Indeed setting `OMP_NUM_THREADS` has no effect, instead, if I set `OMP_BIND_PROC` to some value ("spread", "close", "master", it doesn't matter which one) the number of spawned thread decrease to 6 and the computation seems to run almost completely on a single core (better than original setup). Other OMP environment variables (like `OMP_PLACES`) don't seem to make any change.

My application must run on a single thread (no idle threads, total spawned threads equal to 1). How can I obtain such a result?

**Comment by ilyachur** [comment]
Hi @gasgallo,

First of all I would like to say that the architecture of the Inference Engine doesn't allow to execute inference in the one thread. 

As a minimum the Inference Engine will create 2 additional threads.

Moreover 10 threads it is a really strange number (even if CPU_THREADS, CPU_BIND and other parameters are not set).  At the first sight the code above looks correct and should work. Could you please provide a small reproducer in order to help us to reproduce your problem?

**Comment by gasgallo** [comment]
@ilyachur I reproduced the issue using the `classification_sample` in `deployment_tools/inference_engine/samples` but in this case the number of spawned threads is 6.

I also wanna update the value (10) reported in the initial post, the actual value is 9 (I was counting an extra thread).

**Comment by gasgallo** [comment]
Update: even in my application now I have 6 threads, like in the classification example.

**Comment by shubha-ramani** [comment]
Dear @gasgallo So you compiled IE with OpenMP but you also added some code to classification_sample main.cpp correct ? Can you kindly attach that main.cpp to this github ticket (as a *.zip file probably) ?

Thanks for your patience !

Shubha

**Comment by alalek** [comment]
> must run on a single thread (no idle threads, total spawned threads equal to 1)

@gasgallo Linux system provides tools to control resource scheduling, like `cgroups` (recommended) or simple [`taskset`](https://linux.die.net/man/1/taskset).

**Comment by gasgallo** [comment]
[main.zip](https://github.com/opencv/dldt/files/3332545/main.zip)

@shubha-ramani I attach the main.cpp of the classification example. I simply added the config options to use when loading the network to the plugin (see line 200).
I didn't compile IE, I used what included in the standard OPENVINO installation.

@alalek yes, you're right and I can definitely use the resources you suggested if I cannot run on single thread using IE configuration only.

P.S. I'm currently building IE with -DTHREADING=SEQ, maybe this will give me the expected result.

**Comment by gasgallo** [comment]
Update: if building IE with -DTHREADING=SEQ the number of threads used is reduced to 3.

So even without any multi-threading framework there are multiple threads spawned. How is this possible?

**Comment by elvin-nnov** [comment]
two aditional threads are required to support asynchronious mode and callbacks. They are created everytime for each executable network.

**Comment by gasgallo** [comment]
@elvin-nnov thank you for the information.

 Actually I'm not using async mode or any specific callback. Is there any chance to build IE without support to those and so getting a single-threaded inference?

**Comment by elvin-nnov** [comment]
Unfortunately not for now.
These threads do not consume almost any resources, at least they do not consume runtime ones, they do not have spin loops inside. They can disturb if you are working on some limited environment requiring not to run threads at all.

**Comment by mingzhang96** [comment]
@gasgallo Hi, I am also wondering on how to inference on single thread. It seems that there is no way to attach it using IE configuration only. Could you tell me how you solve this problem? 

Thanks in advance!

**Comment by gasgallo** [comment]
@mingzhang96 Hi, unfortunately I haven't found any solution and I'm not even sure an easy solution exists. I simply switched to a different framework to run the inference.

**Comment by mingzhang96** [comment]
@gasgallo Hi, thanks for your response. Could you tell me which framework you switched to? My application must run on a single thread, maybe I would also switch to other framework.

Thanks!

**Comment by gasgallo** [comment]
@mingzhang96 [TVM](https://github.com/apache/incubator-tvm)

**Comment by mingzhang96** [comment]
@gasgallo Thanks!

**Comment by mingzhang96** [comment]
@elvin-nnov Hi, I want to manually delete codes about creating the two threads for async mode, because I only use sync mode and want my application work on only one thread. Could you give me some advice or show me some detail about the structure of the code? 

Thanks!

**Comment by ngxbac** [comment]
@elvin-nnov , I have same question as @mingzhang96 , please help us. 

Thanks!
