### ISSUE TITLE
why is openblas,  not using mkl to accelerate?

### ISSUE THREAD

**Issue by mmx110** [opencv/dldt#19]

**Comment by mmx110** [comment]
why is openblas,  not using mkl to accelerate?

**Comment by moslex** [comment]
Hello, @mmx110 
MKL is closed source component and it is available in Intel® Distribution of OpenVINO™ toolkit: https://software.intel.com/en-us/openvino-toolkit

OpenBlas is open source and it provides "white box" experience to open source community.
