### ISSUE TITLE
 ssd_mobilenet_v1_coco downloaded from https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md got converted successfully for me using above commands , but when I try for next tensorflow model in the zoo URL as ssd_mobilenet_v1_0.75_depth_coco, it returns following error..

### ISSUE THREAD

**Issue by avaish1** [opencv/dldt#190]
[openvino_ssd_error.txt](https://github.com/opencv/dldt/files/3320211/openvino_ssd_error.txt) Pls refer the attached error file with below problem description. 

Though ssd_mobilenet_v1_coco downloaded from https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md got converted successfully for me using above commands , but when I try for next tensorflow model in the zoo URL as ssd_mobilenet_v1_0.75_depth_coco, it returns following error.. 

Appreciate any quick help.. 

avaish@avaish-B85M-D3H:~/tflite/object_detection/medium_od_3omin/ssd_mobilenet_v1_0.75_depth_300x300_coco14_sync_2018_07_03$ python3  $MO_PATH/mo_tf.py --input_model frozen_inference_graph.pb --tensorflow_use_c
ustom_operations_config /opt/intel/openvino/openvino/deployment_tools/model_optimizer/extensions/front/tf/ssd_support.json --tensorflow_object_detection_api_pipeline_config pipeline.config --data_type=FP32
Model Optimizer arguments:
Common parameters:
	- Path to the Input Model: 	/home/avaish/tflite/object_detection/medium_od_3omin/ssd_mobilenet_v1_0.75_depth_300x300_coco14_sync_2018_07_03/frozen_inference_graph.pb
	- Path for generated IR: 	/home/avaish/tflite/object_detection/medium_od_3omin/ssd_mobilenet_v1_0.75_depth_300x300_coco14_sync_2018_07_03/.
	- IR output name: 	frozen_inference_graph
	- Log level: 	ERROR
	- Batch: 	Not specified, inherited from the model
	- Input layers: 	Not specified, inherited from the model
	- Output layers: 	Not specified, inherited from the model
	- Input shapes: 	Not specified, inherited from the model
	- Mean values: 	Not specified
	- Scale values: 	Not specified
	- Scale factor: 	Not specified
	- Precision of IR: 	FP32
	- Enable fusing: 	True
	- Enable grouped convolutions fusing: 	True
	- Move mean values to preprocess section: 	False
	- Reverse input channels: 	False
TensorFlow specific parameters:
	- Input model in text protobuf format: 	False
	- Path to model dump for TensorBoard: 	None
	- List of shared libraries with TensorFlow custom layers implementation: 	None
	- Update the configuration file with input/output node names: 	None
	- Use configuration file used to generate the model with Object Detection API: 	/home/avaish/tflite/object_detection/medium_od_3omin/ssd_mobilenet_v1_0.75_depth_300x300_coco14_sync_2018_07_03/pipeline.config
	- Operations to offload: 	None
	- Patterns to offload: 	None
	- Use the config file: 	/opt/intel/openvino/openvino/deployment_tools/model_optimizer/extensions/front/tf/ssd_support.json
Model Optimizer version: 	2019.1.1-83-g28dfbfd
The Preprocessor block has been removed. Only nodes performing mean value subtraction and scaling (if applicable) are kept.
[ ERROR ]  Cannot infer shapes or values for node "Postprocessor/ToFloat".
[ ERROR ]  0
[ ERROR ]  
[ ERROR ]  It can happen due to bug in custom shape infer function <function Cast.infer at 0x7f6cabc9b400>.
[ ERROR ]  Or because the node inputs have incorrect values/shapes.
[ ERROR ]  Or because input shapes are incorrect (embedded to the model or passed via --input_shape).
[ ERROR ]  Run Model Optimizer with --log_level=DEBUG for more information.
[ ERROR ]  Exception occurred during running replacer "REPLACEMENT_ID" (<class 'extensions.middle.PartialInfer.PartialInfer'>): Stopped shape/value propagation at "Postprocessor/ToFloat" node. 
 For more information please refer to Model Optimizer FAQ (<INSTALL_DIR>/deployment_tools/documentation/docs/MO_FAQ.html), question #38. 
avaish@avaish-B85M-D3H:~/tflite/

_Originally posted by @avaish1 in https://github.com/opencv/dldt/issues/75#issuecomment-504940839_

**Comment by shubha-ramani** [comment]
Dear @avaish1
It looks like you're using the wrong version of ssd_support.json. I just tried it on 2019R1.1 with success, the below is my command  

> 

> python "c:\Program Files (x86)\IntelSWTools\openvino_2019.1.148\deployment_tools\model_optimizer\mo_tf.py" --input_model frozen_inference_graph.pb --tensorflow_use_custom_operations_config ssd_v2_support.json --tensorflow_object_detection_api_pipeline_config pipeline.config --log_level DEBUG

Please select your ssd_mobilenet_v1_0.75_depth_300x300_coco14_sync_2018_07_03 from those listed in the [validated and tested Model Optimizer Tensorflow Object Detection API List](http://docs.openvinotoolkit.org/latest/_docs_MO_DG_prepare_model_convert_model_Convert_Model_From_TensorFlow.html)

Thanks !

Shubha

**Comment by avaish1** [comment]
thankyou ..it worked .. btw http://download.tensorflow.org/models/object_detection/ssd_mobilenet_v1_coco_2018_01_28.tar.gz with using ssd_support.json only .. but anyway thanx a lot for your quick help.
