### ISSUE TITLE
To which inference engine libraries must I link my code?

### ISSUE THREAD

**Issue by el1995** [opencv/dldt#201]
Hi everyone,

to do accelerated deep learning inference I need to use OpenVINO's inference engine from another C++ tool, called OpenFOAM. I programmed my inference code into my OpenFOAM executable, and compiled it. To compile within OpenFOAM I must use "wmake", which requires the header files and shared libraries. The headers I provided are here:
/opt/intel/openvino/inference_engine/include
The libraries I provided are here:
/opt/intel/openvino/inference_engine/lib/intel64/

My code compiled properly, however now if I run my application "tabulatedCombustionFoam" I get this error:

```
tabulatedCombustionFoam: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /home/elias/OpenFOAM/elias-4.1/platforms/linux64GccDPInt64Opt/lib/libinference_engine.so)
tabulatedCombustionFoam: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/elias/OpenFOAM/elias-4.1/platforms/linux64GccDPInt64Opt/lib/libinference_engine.so)
tabulatedCombustionFoam: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /home/elias/OpenFOAM/elias-4.1/platforms/linux64GccDPInt64Opt/lib/libinference_engine.so)
tabulatedCombustionFoam: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /home/elias/OpenFOAM/elias-4.1/platforms/linux64GccDPInt64Opt/lib/libinference_engine.so)
tabulatedCombustionFoam: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/elias/OpenFOAM/elias-4.1/platforms/linux64GccDPInt64Opt/lib/libinference_engine.so)
```

I know the problem from another software, checking the versions gives me:

```
strings /lib64/libstdc++.so.6 | grep GLIBC

GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBC_2.3
GLIBC_2.2.5
GLIBC_2.14
GLIBC_2.4
GLIBC_2.3.2
GLIBCXX_DEBUG_MESSAGE_LENGTH
```

```
strings /lib64/libstdc++.so.6 | grep CXXABI

CXXABI_1.3
CXXABI_1.3.1
CXXABI_1.3.2
CXXABI_1.3.3
CXXABI_1.3.4
CXXABI_1.3.5
CXXABI_1.3.6
CXXABI_1.3.7
CXXABI_TM_1
```

For the other software, the problem was that I must use gcc 4.8.5 on CentOS 7.6. However, there are two reasons why I do not understand OpenVINO's inference engine gives me this error here:
1) According to this page (https://software.intel.com/en-us/openvino-toolkit/choose-download/free-download-linux) OpenVINO should work with gcc >=3.4, and it is stated that it is compatible to CentOS
2) Most surprising: I did the entire installation with the same hard- and software. I was able to build all the Intel samples using cmake, I was also able to create my own code (a copy of hello_autoresize_classification) and run it. So obviously, there it works. I do not see why it did not require the new GLIBCXXs / GLIBCs and CXXABIs for my sample build, but now it does.

Thanks in advance for any help,

Elias

_____________________________
Environment:
CentOS Version: CentOS Linux release 7.6.1810 (Core)
gcc Version: gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36)
OpenVINO version: 2019.1.144

**Comment by el1995** [comment]
Ok, now my errors have changed, so I decide to give an update directly. First of all, to show my inference engine code, here are the relevant parts of the class that I added it to:

Header: FPVANNModel.H
```
#ifndef FPVANNModel_H
#define FPVANNModel_H

//#include "OVInfer.H"
#include <iomanip>
#include <vector>
#include <memory>
#include <string>
#include <cstdlib>
#include <map>
#include <list>
#include <limits>
#include <random>
#include <cctype>
#include <functional>
#include <time.h>
#include <iostream>
#include <fstream>
#include <utility>
#include <algorithm>
#include <chrono>
#include <ie_plugin_dispatcher.hpp>
#include <ie_plugin_ptr.hpp>
#include <cpp/ie_cnn_net_reader.h>
#include <cpp/ie_infer_request.hpp>
#include <ie_device.hpp>
#include <ie_blob.h>
#include <opencv2/opencv.hpp>
#include <inference_engine.hpp>
[...]
```

CPP-file: FPVANNModel.C:
```
#include "FPVANNModel.H"
[...]
if(InferenceMode==3)  // OpenVINO
            {
             	auto t_start = std::chrono::high_resolution_clock::now();

                char cwd[256];
                getcwd(cwd,sizeof(cwd));
                const std::string case_directory(cwd);
                const std::string path_to_xml = "/data/FPV_ANN_Standard.xml";
                const std::string full_path = cwd + path_to_xml;
                //const char* binGraphName = full_path.c_str(); // if memory leak occurs maybe check this

                const size_t no_of_inputs = in_mean.size();
                const size_t no_of_outputs = out_mean.size();
                const size_t cellsAndPatches = (input_f_zeta_PVNorm.size())/no_of_inputs;

                InferenceEngine::InferencePlugin plugin = InferenceEngine::PluginDispatcher().getPluginByDevice("CPU");
                InferenceEngine::CNNNetReader network_reader;
                network_reader.ReadNetwork(full_path);
                network_reader.ReadWeights(full_path.substr(0,full_path.size()-4)+".bin");

                network_reader.getNetwork().setBatchSize(cellsAndPatches);
                InferenceEngine::CNNNetwork network = network_reader.getNetwork();

                InferenceEngine::InputInfo::Ptr input_info = network.getInputsInfo().begin()->second;
                std::string input_name = network.getInputsInfo().begin()->first;
                input_info->setLayout(InferenceEngine::Layout::NC);
                input_info->setPrecision(InferenceEngine::Precision::FP32);

InferenceEngine::DataPtr output_info = network.getOutputsInfo().begin()->second;
                std::string output_name = network.getOutputsInfo().begin()->first;
                output_info->setPrecision(InferenceEngine::Precision::FP32);

                InferenceEngine::ExecutableNetwork executable_network = plugin.LoadNetwork(network, {});
                InferenceEngine::InferRequest infer_request = executable_network.CreateInferRequest();

                cv::Mat combustionIn = cv::Mat(cellsAndPatches,no_of_inputs,CV_32FC1);
                for(size_t batchCounter=0;batchCounter<cellsAndPatches;batchCounter++)
                {
                    for(size_t inputCounter=0;inputCounter<no_of_inputs;inputCounter++)
                    {
                     	combustionIn.at<float>(batchCounter,inputCounter) = input_f_zeta_PVNorm.at(batchCounter*no_of_inputs+inputCounter);
                    }
                }

                InferenceEngine::TensorDesc tDescCombustion(InferenceEngine::Precision::FP32,{cellsAndPatches,no_of_inputs},InferenceEngine::Layout::NC);
                InferenceEngine::Blob::Ptr combustionBlob = InferenceEngine::make_shared_blob<float>(tDescCombustion,reinterpret_cast<float*>(combustionIn.data));
                infer_request.SetBlob(input_name,combustionBlob);

                infer_request.Infer();
                InferenceEngine::Blob::Ptr output = infer_request.GetBlob(output_name);
                InferenceEngine::Blob* pointerToOutput = output.get();

                float* decode_blob = pointerToOutput->buffer().as<float*>();

                output_real.clear();
                output_real.resize(cellsAndPatches*no_of_outputs);

for(size_t i=0;i<no_of_outputs;i++)
                {
                    output_real.at(i) = *decode_blob;
                    decode_blob++;
                }

                auto t_end = std::chrono::high_resolution_clock::now();
                auto total = std::chrono::duration<float, std::milli>(t_end - t_start).count();
                Info << "Total inference time ONNX Runtime: " << total << endl;
                float throughput = (cellsAndPatches/total)*1000;
                Info << "Total throughput OpenVINO Inference engine: " << throughput << endl;
}
```
As I mentioned I must compile the code using "wmake". This requires the headers and libraries (.so) that the code above needs. My CPUs support AVX2 and SSE4, therefore I would like to activate these.

**Comment by el1995** [comment]
Ok so the last error with the undefined symbol could be solved by not using OpenCV within the project. Now the code is running, but I am still unsure about the library usage... is it sufficient to link these libraries?

```
libinference_engine.so
libMKLDNNPlugin.so
libcpu_extension_avx2
libcpu_extension_sse4
```
Does that automatically activate avx2 and sse4 usage? And do I even have to install OpenVINO if I just want to use the inference engine? Or is it enough to include the required headers and link to the 4 libraries above?

**Comment by shubha-ramani** [comment]
Dear @el1995,

You can certainly build a standalone OpenVino application as long as you have all the required libraries.  Anything under inference-engine\bin is fair game for libs which need to be included in a standalone project. 

But to make sure you got everything you need, please use a tool like [binscan](https://sourceforge.net/projects/binscan/) or [Elf Library Viewer](http://www.purinchu.net/software/elflibviewer.php) or in the case of Windows [Dependency Walker](http://www.dependencywalker.com/)

I'm sure you realize that these tools don't lie. If you have the required OpenVino libraries _**and their dependencies**_ in your standalone project then there is no reason to install OpenVino on a your client's machine.

Hope it helps,

Thanks,

Shubha

**Comment by el1995** [comment]
Hello Shubha,

thanks for your reply, I will check asap with the recommended tools. I have two remaining questions regarding the linked so libraries:

1) During compilation and runtime, the inference engine asks for the library ```libcpu_extension```. I did not find it in the inference engine libraries folder, insted it was located here:
```/inference_engine_samples_build/intel64/Release/lib```
I assume it is built together with the samples. Does it already activate the available instruction set architectures (AVX2 etc) or not? What is it required for?
2) I so far linked the libraries for avx2, sse4 etc to my code. Do they activate the ISAS or is it done with the library mentioned in 1)? How can I make sure I get the maximum ISAs my machine offers?

Best regards and thanks in advance!

**Comment by shubha-ramani** [comment]
Dear @el1995 
Yeah you definitely need libcpu_extension also. And yes, it's built together with the samples. It's required for  all the extension code you see here (see below) - these are layer (wrapping  an operation) implementations on the CPU hardware.
[https://github.com/opencv/dldt/tree/2019/inference-engine/src/extension](https://github.com/opencv/dldt/tree/2019/inference-engine/src/extension)

If your machine supports AVX512, an avx512 extension should be built automatically. The build system uses CPUID to figure out which ISAs your system supports. For instance please look at at this file:

> inference-engine\src\extension\cmake\CPUID.cmake

So the burden is not upon you to determine whether the right ISAs are included. Rather it's on the Inference Engine and Extension code build system.

Hope it helps !

Shubha

**Comment by el1995** [comment]
Helped, thank you very much!
