### ISSUE TITLE
How can I get the output through any API ?

### ISSUE THREAD

**Issue by Fighting-JJ** [opencv/dldt#204]
In the demo, 

        std::string outputName;
        DataPtr outputInfo;
        for (const auto& out : outputsInfo) {
            if (out.second->creatorLayer.lock()->type == "DetectionOutput") {
                outputName = out.first;
                outputInfo = out.second;
            }
        }

If  i run my IR model,  what should i do ?

**Comment by shubha-ramani** [comment]
Dear @Fighting-JJ 
I think I understand what you mean but I'm not sure. Are you talking about getting the output tensor from intermediate layers or being able to dump output layers before and after inference ?
If so, please look at [this idz post](https://software.intel.com/en-us/forums/computer-vision/topic/804937)

The object_detection_demo mentioned in that IDZ post is not available in dldt. But if you do a grep on "addOutput" within dldt you get lots of hits. 

Please see how addOutput is used

> 
inference-engine\ie_bridges\python\src\openvino\inference_engine\ie_api_impl.cpp:153:InferenceEnginePython::IENetwork::
addOutputs(const std::vector<std::string> &out_layers, const std::string &precision) {
inference-engine\ie_bridges\python\src\openvino\inference_engine\ie_api_impl.cpp:166:        actual.addOutput(l);
inference-engine\samples\calibration_tool\calibrator_processors.cpp:208:                network.addOutput(layer->name);
inference-engine\samples\calibration_tool\calibrator_processors.cpp:407:            network.addOutput(layer->name);
inference-engine\src\cldnn_engine\cldnn_graph.cpp:552:        AddOutputPrimitive(output.first, output.second);
inference-engine\src\cldnn_engine\cldnn_graph.cpp:3549:void CLDNNGraph::AddOutputPrimitive(std::string outputName,
const InferenceEngine::DataPtr outputData, Precision outputPrecision) {
inference-engine\src\hetero_plugin\hetero_executable_network.cpp:227:                tempNetwork->addOutput(il->name);
inference-engine\src\inference_engine\builders\ie_network_builder.cpp:666:
cnnNetworkImpl->addOutput(data->getName());
inference-engine\src\inference_engine\cnn_network_impl.cpp:141:StatusCode CNNNetworkImpl::addOutput(const std::string&
layerName, size_t outputIndex, ResponseDesc* resp) noexcept {
inference-engine\src\inference_engine\cnn_network_impl.cpp:168:void CNNNetworkImpl::addOutput(const string& dataName) {
inference-engine\src\inference_engine\ie_format_parser.cpp:21:void LayerParseParameters::addOutputPort(const
LayerPortData &port) {
inference-engine\src\inference_engine\ie_format_parser.cpp:87:            layerParsePrms.addOutputPort(port);
inference-engine\src\inference_engine\ie_layer_parsers.cpp:120:            auto sts = net->addOutput(layer->name,
o_idx, nullptr);
inference-engine\src\inference_engine\ie_util_internal.cpp:198:        net->addOutput(o.first);
inference-engine\src\inference_engine\ie_util_internal.cpp:287:                    net->addOutput(data->getName());
inference-engine\src\vpu\graph_transformer\src\frontend\parse_data.cpp:63:        auto vpuData =
model->addOutputData(ieData->getName(), vpuDesc);
inference-engine\src\vpu\graph_transformer\src\model\model.cpp:77:Data Model::addOutputData(
inference-engine\tests\unit\engines\gna\i16_quantisation_test.cpp:179:            net.addOutput("Eltwise_8");
inference-engine\tests\unit\engines\mkldnn\graph\layers\internal\graph_leaks_test.cpp:44:    void
addOutputToEachNode(InferenceEngine::CNNNetReader& net_reader, std::vector<std::string>& new_outputs,
inference-engine\tests\unit\engines\mkldnn\graph\layers\internal\graph_leaks_test.cpp:50:
net_reader.getNetwork().addOutput(cnnLayer->name);
inference-engine\tests\unit\engines\mkldnn\graph\layers\internal\graph_leaks_test.cpp:55:
addOutputToEachNode(net_reader, new_outputs, data.second);
inference-engine\tests\unit\engines\mkldnn\graph\layers\internal\graph_leaks_test.cpp:258:
addOutputToEachNode(net_reader, new_outputs, layer.second);
inference-engine\tests\unit\engines\mkldnn\graph\layers\internal\graph_reorder_test.cpp:209:
net_reader.getNetwork().addOutput("reshape1");
inference-engine\tests\unit\engines\mkldnn\graph\structure\graph_structure_test.cpp:6379:
reader.getNetwork().addOutput("split");
inference-engine\tests\unit\engines\mkldnn\graph\structure\graph_structure_test.cpp:6527:    net.addOutput("split", 0);
inference-engine\tests\unit\engines\vpu\adjust_data_location_tests.cpp:38:    auto output1 =
model->addOutputData("Output 1", dataDesc2);
inference-engine\tests\unit\engines\vpu\adjust_data_location_tests.cpp:39:    auto output2 =
model->addOutputData("Output 2", dataDesc2);
inference-engine\tests\unit\engines\vpu\adjust_data_location_tests.cpp:40:    auto output3 =
model->addOutputData("Output 3", dataDesc2);
inference-engine\tests\unit\engines\vpu\adjust_data_location_tests.cpp:41:    auto output4 =
model->addOutputData("Output 4", dataDesc2);
inference-engine\tests\unit\engines\vpu\eliminate_copy_tests.cpp:22:    auto output1 = model->addOutputData(
inference-engine\tests\unit\engines\vpu\eliminate_copy_tests.cpp:25:    auto output2 = model->addOutputData(
inference-engine\tests\unit\engines\vpu\find_subgraphs_tests.cpp:30:        auto output = model->addOutputData(
inference-engine\tests\unit\engines\vpu\graph_transformer_tests_constructs.cpp:22:    auto output =
model->addOutputData(
inference-engine\tests\unit\engines\vpu\replace_deconv_by_conv_tests.cpp:38:            output = model->addOutputData(
inference-engine\tests\unit\engines\vpu\replace_deconv_by_conv_tests.cpp:44:            output = model->addOutputData(

**Comment by Fighting-JJ** [comment]
@shubha-ramani  Thanks for your reply.  The outputsInfo contains the output  layers' name whose are same as described in the xml file.
