### ISSUE TITLE
the cpu sdk does not support FP16?

### ISSUE THREAD

**Issue by jlygit** [opencv/dldt#205]
hello,
i run a model and it throws that:
terminate called after throwing an instance of 'InferenceEngine::details::InferenceEngineException'
  what():  The plugin does not support FP16

i don't know what happen.

**Comment by shubha-ramani** [comment]
Dearest @jlygit 
It's true that in 2019R1.1 FP16 is not supported by the CPU Plugin. However in the next release R2 (coming very soon) FP16 is supported by CPU.

Thanks for your patience,

Shubha

**Comment by jlygit** [comment]
@shubha-ramani

**Comment by jlygit** [comment]
hello @shubha-ramani 

i update to the release R2 and query_device say that it don't support  FP16 , what happen?
![image](https://user-images.githubusercontent.com/10195989/62203033-fd83af00-b3bc-11e9-88e9-aa25224b2c8d.png)

**Comment by shubha-ramani** [comment]
Dear @jlygit 
That seems like a bug. FP16  support on CPU (called "serialized FP16") is definitely supported on the CPU in R2. I will file a bug on your behalf because this query should reflect FP16 support, evne if it's called "Serialized FP16" or something along those lines. 

Thanks for your detective work !

Shubha

**Comment by elvin-nnov** [comment]
We need to distinguish runtime and data format for storing of model. The CPU plugin still supports only FP32/int8 and bin computation but you can feed FP16 model. During loading of the model, it would be converted to fp32 and executed in fp32 mode. That optimization_capabilities properties belongs to computation abilities

**Comment by jlygit** [comment]
@elvin-nnov 
it is says that the FP16 computation is not supportted by the  release R2.
Is there planned support for future versions.

thanks

**Comment by elvin-nnov** [comment]
it is correct. FP32/I8/binary computation is supported with fp32/fp16 IR. Why are you looking for fp16 inference? There is no sence on CPU.

**Comment by jlygit** [comment]
@elvin-nnov 
i want to know that if  fp16 inference can speed up the Inference by half. This can help me increase the fps,,,

**Comment by elvin-nnov** [comment]
fp16 inference can speedup infernece by half if there is special support in the hardware. Currently CPU have only instructions for conversion FP16<->FP32, but not processing of data in fp16.
I propose to close an issue, since current behaviour is expected.
