### ISSUE TITLE
Failed to load  CNNNetwork network by Core API

### ISSUE THREAD

**Issue by Fighting-JJ** [opencv/dldt#210]
Great job for the openVINO-version2. But there is still something do not work well.

Here is the C++ code.

```
	Core core;
	// Create an IR reader
	CNNNetReader network_reader;
	const std::string Model_xml = "E:/OpenVINO2_test/Refinedet_Anysize.xml";
	const std::string Model_bin = "E:/OpenVINO2_test/Refinedet_Anysize.bin";
	//const std::string Model_xml = "E:/lipeng_code/OpenVINO_test/Refinedet.xml";
	//const std::string Model_bin = "E:/lipeng_code/OpenVINO_test/Refinedet.bin";


	network_reader.ReadNetwork(Model_xml);
	network_reader.ReadWeights(Model_bin);

	// Configure input and output.
	auto network = network_reader.getNetwork();
	/** Taking information about all topology inputs **/
	InferenceEngine::InputsDataMap input_info(network.getInputsInfo());
	/** Taking information about all topology outputs **/
	InferenceEngine::OutputsDataMap output_info(network.getOutputsInfo());

	/** Iterating over all input info**/
	for (auto &item : input_info) {
		auto input_data = item.second;
		input_data->setPrecision(Precision::FP32);
		input_data->setLayout(Layout::NCHW);
		input_data->getPreProcess().setResizeAlgorithm(RESIZE_BILINEAR);
	}
	/** Iterating over all output info**/
	for (auto &item : output_info) {
		auto output_data = item.second;
		output_data->setPrecision(Precision::FP32);
		output_data->setLayout(Layout::CHW); 
	}

	/** Load the model to the plugin **/
	/*auto executable_network = plugin.LoadNetwork(network, {});*/
	auto executable_network = core.LoadNetwork(network, "CPU");

	/* Create an infer reques t*/
	auto infer_request = executable_network.CreateInferRequest();
```
the code failed at line:
`auto executable_network = core.LoadNetwork(network, "CPU");`

if do not replace the Plugins API with Core API,  there will be error info too,:
`错误	LNK2019	无法解析的外部符号 "__declspec(dllimport) public: __cdecl InferenceEngine::PluginDispatcher::PluginDispatcher(class std::vector<class std::basic_string<wchar_t,struct std::char_traits<wchar_t>,class std::allocator<wchar_t> >,class std::allocator<class std::basic_string<wchar_t,struct std::char_traits<wchar_t>,class std::allocator<wchar_t> > > > const &)" (__imp_??0PluginDispatcher@InferenceEngine@@QEAA@AEBV?$vector@V?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@V?$allocator@V?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@@2@@std@@@Z)，该符号在函数 main 中被引用	OpenVINO2_test	E:\lipeng_code\OpenVINO2_test\OpenVINO2_test\test_OpenVino.obj	1	
`

**Comment by Fighting-JJ** [comment]
@openvino-pushbot Need some tips to get the code work.

**Comment by shubha-ramani** [comment]
Dearest @Fighting-JJ 
I'm very sorry to hear this ! Can you attach your code as a main.cpp and allow me to reproduce your issue ?

Thanks - I will take a look.

Shubha

**Comment by Fighting-JJ** [comment]
> Dearest @Fighting-JJ
> I'm very sorry to hear this ! Can you attach your code as a main.cpp and allow me to reproduce your issue ?
> 
> Thanks - I will take a look.
> 
> Shubha

wiht the fllowing code , the Core Api can work. But the way in which it works  is unreasonable.
core.AddExtension(std::make_shared<Extensions::Cpu::CpuExtensions>(), "CPU");

**Comment by Fighting-JJ** [comment]
> Dearest @Fighting-JJ
> I'm very sorry to hear this ! Can you attach your code as a main.cpp and allow me to reproduce your issue ?
> 
> Thanks - I will take a look.
> 
> Shubha

Another ERROR happens. I have no idea about it.
Because the slice op in onnx do not work perfectly, so i replace the slice op wiht torch.split.
Then I got the Onnx model without Warning infomation. Next I convert onnx model to IR model successfully.

when runs into  infer_request.Infer() , then Another Error comes:
 Assertion failed: sizeof...(args) == ndims(), file C:\bld\releases\2019\R2\thirdparty\mkl-dnn\src\common\memory_desc_wrapper.hpp, line 314

```
#include <ie_core.hpp>
#include <ie_extension.h>
#include <ie_iextension.h>
#include <cpp/ie_cnn_net_reader.h>
#include <inference_engine.hpp>
#include <ie_icnn_network.hpp>
#include <ie_icnn_network_stats.hpp>
#include <ie_core.hpp>
#include <ie_utils.hpp>
#include <cpp/ie_cnn_net_reader.h>
#include <cpp/ie_plugin_cpp.hpp>
#include <cpp/ie_executable_network.hpp>
#include <vpu/vpu_plugin_config.hpp>
#include <ext_list.hpp>
#include <map>
#include <memory>
#include <string>
#include <vector>
#include <opencv2/opencv.hpp>
#include <time.h>
#include <limits>
#include <chrono>

#define NMS_SCORE_THRES  0.95

#define TEST_TIME true
#define DEBUG true
using namespace InferenceEngine;
using namespace std;

int main()
{
	// Load a plugin 
	//InferenceEnginePluginPtr engine_ptr = PluginDispatcher().getSuitablePlugin(TargetDevice::eCPU);
	//InferencePlugin plugin(engine_ptr);
	Core core;
	core.AddExtension(std::make_shared<Extensions::Cpu::CpuExtensions>(), "CPU");
	// Create an IR reader
	CNNNetReader network_reader;
	const std::string Model_xml = "E:/OpenVINO2_test/Refinedet_Anysize.xml";
	const std::string Model_bin = "E:/OpenVINO2_test/Refinedet_Anysize.bin";
	network_reader.ReadNetwork(Model_xml);
	network_reader.ReadWeights(Model_bin);

	// Configure input and output.
	auto network = network_reader.getNetwork();
	/** Taking information about all topology inputs **/
	InferenceEngine::InputsDataMap input_info(network.getInputsInfo());
	/** Taking information about all topology outputs **/
	InferenceEngine::OutputsDataMap output_info(network.getOutputsInfo());

	/** Iterating over all input info**/
	for (auto &item : input_info) {
		auto input_data = item.second;
		input_data->setPrecision(Precision::FP32);
		input_data->setLayout(Layout::NCHW);
		input_data->getPreProcess().setResizeAlgorithm(RESIZE_BILINEAR);
	}
	/** Iterating over all output info**/
	for (auto &item : output_info) {
		auto output_data = item.second;
		output_data->setPrecision(Precision::FP32);
		output_data->setLayout(Layout::CHW); 
	}
	/** Load the model to the plugin **/
	/*auto executable_network = plugin.LoadNetwork(network, {});*/
	auto executable_network = core.LoadNetwork(network, "CPU");

	/* Create an infer reques t*/
	auto infer_request = executable_network.CreateInferRequest();

	const string input_path = "E:/out_test/fk7WSAqg_0.jpg";
	cv::Mat OrigImage = cv::imread(input_path);
	cv::cvtColor(OrigImage, OrigImage, cv::COLOR_RGB2BGR);
	cv::Mat input_Mat;
	OrigImage.convertTo(input_Mat, CV_32F, 1.0 / 255);
	cv::resize(input_Mat, input_Mat, cv::Size(256, 64), 0, 0, cv::INTER_LINEAR);
	char* Mat_data = (char*)input_Mat.data;

	/** Iterating over all input blobs **/
	for (auto &item : input_info) {
		auto input_name_net = item.first;
		/** Getting input blob **/
		auto input_net = infer_request.GetBlob(input_name_net);
		size_t num_channels = input_net->getTensorDesc().getDims()[1];
		size_t image_size = input_net->getTensorDesc().getDims()[3] * input_net->getTensorDesc().getDims()[2];
		float* data = static_cast<float*>(input_net->buffer());
		/** Iterate over all input images **/
		/** Iterate over all pixel in image (b,g,r) **/
		for (size_t pid = 0; pid < image_size; pid++) {
			/** Iterate over all channels **/
			for (size_t ch = 0; ch < num_channels; ++ch) {
				/**          [images stride + channels stride + pixel id ] all in bytes            **/
				float temp = *((float*)(Mat_data + pid * num_channels * sizeof(float) + ch * sizeof(float)));
				data[ch * image_size + pid] = temp;
			}
		}
	}
	/*Do inference*/
	//infer_request.StartAsync();
	//infer_request.Wait(IInferRequest::WaitMode::RESULT_READY);
	infer_request.Infer();
#if TEST_TIME
	typedef std::chrono::high_resolution_clock Time;
	typedef std::chrono::duration<double, std::ratio<1, 1000>> ms;
	typedef std::chrono::duration<float> fsec;

	double total = 0.0;
	/** Start inference & calc performance **/
	for (size_t iter = 0; iter < 100; ++iter) {
		auto t0 = Time::now();
		infer_request.Infer();
		auto t1 = Time::now();
		fsec fs = t1 - t0;
		ms d = std::chrono::duration_cast<ms>(fs);
		total += d.count();
	}
	std::cout << std::endl << "total inference time: " << total << std::endl;
	std::cout << "Average running time of one iteration: " << total / static_cast<double>(100) << " ms" << std::endl;
	std::cout << std::endl;
#endif
	cv::Mat Output_Refinedet(16128, 7, CV_32F);
	for (auto &item : output_info) {
		auto output_name = item.first;
		auto output = infer_request.GetBlob(output_name);
		auto const memLocker = output->cbuffer(); // use const memory locker
													// output_buffer is valid as long as the lifetime of memLocker
		const float *output_buffer = memLocker.as<const float *>();
		if (output_name == "425")
		{
			std::memcpy((void*)Output_Refinedet.data, (void*)output_buffer, sizeof(float) * 16128 * 7 );
		}
		else
		{
			continue;
		}
	}


	cout << "test" << endl;
	return 0;
}
```

the xml file :
[Refinedet_Anysize.zip](https://github.com/opencv/dldt/files/3434037/Refinedet_Anysize.zip)

**Comment by shubha-ramani** [comment]
Dear @Fighting-JJ 
Why is this unreasonable ?

> with the fllowing code , the Core Api can work. But the way in which it works is unreasonable.
core.AddExtension(std::make_sharedExtensions::Cpu::CpuExtensions(), "CPU");

As I related to [This forum poster ](https://software.intel.com/en-us/forums/computer-vision/topic/814958) the Slice Op for ONNX in OpenVino R2 should definitely be supported. Are you using OpenVino R2 ?

Thanks,

Shubha

**Comment by Fighting-JJ** [comment]
> 
> 
> Dear @Fighting-JJ
> Why is this unreasonable ?
> 
> > with the fllowing code , the Core Api can work. But the way in which it works is unreasonable.
> > core.AddExtension(std::make_sharedExtensions::Cpu::CpuExtensions(), "CPU");
> 
> As I related to [This forum poster ](https://software.intel.com/en-us/forums/computer-vision/topic/814958) the Slice Op for ONNX in OpenVino R2 should definitely be supported. Are you using OpenVino R2 ? The existence of C:\Program Files (x86)\IntelSWTools\openvino_2019.2.242\deployment_tools\model_optimizer\extensions\front\onnx\slice_ext.py means that the slice op for ONNX is likely supported in R2. Unfortunately our documentation for R2 is about a week behind but it will be updated soon. According to [Supported Framework Layers R1](http://docs.openvinotoolkit.org/latest/_docs_MO_DG_prepare_model_Supported_Frameworks_Layers.html) slice is not a supported Op for ONNX in R1.
> 
> Thanks,
> 
> Shubha

In the official guide of inference Engine docement,  core.AddExtension() API is not neccesery. That means the Core API can work well without core.AddExtension().  
In your demos, once Core API   was used, core.AddExtension()  was called.  
and the extra .lib\.dll file for ` core.AddExtension()`   do not exsit in the software,  the users can only use the  ` core.AddExtension()`  after compiling the official demos .
so , it is unreasonable , in other words , it is unfriendly to users.

**Comment by Fighting-JJ** [comment]
> 
> 
> Dear @Fighting-JJ
> Why is this unreasonable ?
> 
> > with the fllowing code , the Core Api can work. But the way in which it works is unreasonable.
> > core.AddExtension(std::make_sharedExtensions::Cpu::CpuExtensions(), "CPU");
> 
> As I related to [This forum poster ](https://software.intel.com/en-us/forums/computer-vision/topic/814958) the Slice Op for ONNX in OpenVino R2 should definitely be supported. Are you using OpenVino R2 ? The existence of C:\Program Files (x86)\IntelSWTools\openvino_2019.2.242\deployment_tools\model_optimizer\extensions\front\onnx\slice_ext.py means that the slice op for ONNX is likely supported in R2. Unfortunately our documentation for R2 is about a week behind but it will be updated soon. According to [Supported Framework Layers R1](http://docs.openvinotoolkit.org/latest/_docs_MO_DG_prepare_model_Supported_Frameworks_Layers.html) slice is not a supported Op for ONNX in R1.
> 
> Thanks,
> 
> Shubha

Yes, the slice operation is supported, but there still be somthing wrong in the process of converting pytorch model to IR model , maybe the process of converting pytorch model to onnx . 

Thanks for your reply, Shubha
