### ISSUE TITLE
Cannot find plugin to use on Raspberry

### ISSUE THREAD

**Issue by paulbauriegel** [opencv/dldt#218]
I compiled DLDT for a Rasperry Pi 3 following the building instructions, but for some reason loading plugins does not work. I tried the some of the samples and the error is always the same.

`./object_detection_sample_ssd -i ~/test.jpg -m ~/face-detection-adas-binary-0001.xml -pp ~/dldt/inference-engine/bin/armv7l/Release/lib -d CPU`

```
[ INFO ] InferenceEngine: 
	API version ............ 1.6
	Build .................. custom_2019_c585b530c1b969930df61252057ccea2f72dfc76
Parsing input parameters
[ INFO ] Files were added: 1
[ INFO ]     /home/pi/test.jpg
[ INFO ] Loading plugin
[ ERROR ] Cannot find plugin to use :
```

**Comment by shubha-ramani** [comment]
Dear @paulbauriegel 
Did you set your environment properly first by running setupvars.sh ? Also do you have a Movidious stick (i.e. NCS) ? A raspberry PI is an ARM host so -d CPU will not work. You must do -d MYRIAD, with an NCS2 plugged into your raspberry pi board. If you want to use CPU then kindly install OpenVino on a supported Intel CPU.

Hope it helps,

Thanks,

Shubha

**Comment by paulbauriegel** [comment]
@shubha-ramani Thanks for your response. I don't have a Movidius stick. Do you mean that dldt/OpenVINO does not run on a ARM CPU at all?

**Comment by shubha-ramani** [comment]
Dear @paulbauriegel Yes this is exactly what I mean. OpenVino does not run on ARM CPU because a plugin for ARM CPU does not exist.

Thanks,

Shubha
