### ISSUE TITLE
Problem About Inference Engine Neural Network Builder

### ISSUE THREAD

**Issue by junluan** [opencv/dldt#247]
Hi,

I have tried the builder api and there are some problems with the ConcatLayer builder. For example this code bellow will be core dumped when connect input layer with concat layer

Exception: EXC_BAD_ACCESS (code=1, address=0x20)

I have tested this in my Mac with openvino_2019.2.275.

```
Builder::Network graph("test");
auto input_id = graph.addLayer(Builder::InputLayer("in").setPort(Port({1, 3, 224, 224})));
auto concat_id = graph.addLayer({{input_id, 0}, {input_id, 0}}, Builder::ConcatLayer("concat").setAxis(1));
```

Another thing I want to know is when does builder do shape inference.

**Comment by shubha-ramani** [comment]
Dear @junluan 
Can you kindly attach your code to this ticket and let me try to reproduce your error ? It may not have anything to do with Mac OSX actually.

Thanks,

Shubha

**Comment by shubha-ramani** [comment]
Dear @junluan 
Is your code exactly like this file ?
C:\intel\dldt\inference-engine\tests\unit\builders\concat_layer_test.cpp ?

Please study that file for guidance. That test should work (but definitely let me know if it doesn't).

thanks,

Shubha

**Comment by dkurt** [comment]
Please try to use setInputPorts to specify number of inputs.

You may check OpenCV source code for reference of how to use DNNBuilder: https://github.com/opencv/opencv/blob/master/modules/dnn/src/layers/concat_layer.cpp.

**Comment by junluan** [comment]
Thank you very much. @shubha-ramani @dkurt 

ConcatLayer needs setInputPorts to work.

Another thing I want to know is that can builder infer shapes when I build the network. For example, when I add one layer, can I get the layer output port shapes.

I have test this code below. The relu layer's output port's shape will be empty. 

```
Builder::Network graph("test");
auto input_id = graph.addLayer(Builder::InputLayer("in").setPort(Port({1, 3, 224, 224})));
auto relu_id = graph.addLayer({input_id}, Builder::ReLULayer("relu").setNegativeSlope(0.f));
auto relu_layer = graph.getLayer(relu_id);
auto shape = relu_layer.getOutputPorts()[0].shape();
```

I think there may have some functions to do shape inference. What I found is [getShapeInferImpl](https://github.com/opencv/dldt/blob/2019/inference-engine/include/ie_context.hpp#L44) function in ie_context.hpp. Is this the only way I can get layer output shapes?

Thank you.

**Comment by shubha-ramani** [comment]
Dear @junluan 
There is also getShapeInferTypes . Kindly take a look at the tests under C:\intel\dldt\inference-engine\tests\unit\shape_infer\

Hope it helps,

Thanks,

Shubha
