### ISSUE TITLE
/opt/intel/openvino/deployment_tools/tools/cl_compiler/clc: No such file or directory

### ISSUE THREAD

**Issue by QLSong** [opencv/dldt#249]
I want to create my operator for stick2,but I find I don't
have this compiler.

**Comment by shubha-ramani** [comment]
Dear @QLSong 

May I ask which version of OpenVino you installed ? And from where did you get the install package ? They typical OpenVino installation does not have cl_compiler under deployment_tools/tools. What I would recommend is to uninstall your existing, older OpenVino installation(s) and download the latest and greatest - which is 2019R2.01.

Thanks,

Shubha

**Comment by QLSong** [comment]
when I reinstall the toolkit with FPGA Support, I find it.And I have created my operator for stick2 successfully, thank you very much.

**Comment by shubha-ramani** [comment]
Dear @QLSong 
This is great. So happy you solved your problem ! Can you kindly close this ticket then ?

Thanks,

Shubha
