### ISSUE TITLE
RuntimeError: [VPU] Kernel binary exceeds 16KB

### ISSUE THREAD

**Issue by QLSong** [opencv/dldt#258]
hi, when I run my code,this mistake occured.my code is as follow:

net = IENetwork(model = 'refinedet_resnet18_vehicle_v3.xml', weights = 'refinedet_resnet18_vehicle_v3.bin')
    ie = IECore()
    ie.set_config({'VPU_CUSTOM_LAYERS': 'decode_box.xml'}, 'MYRIAD')
    input_info = net.inputs
    input_name = next(iter(input_info))
    out_name = next(iter(net.outputs))
    crnn_net = ie.load_network(net, 'MYRIAD')

decode_box.bin is 30K,what should I do?

**Comment by shubha-ramani** [comment]
Dear @QLSong,
So far I'm not seeing the mistake you made in your code. Can you kindly paste the exact error message you're getting during inference  (model loading) ?

Thanks,

Shubha

**Comment by shubha-ramani** [comment]
Dear @QLSong 
OK. It looks like your runtime error is the title of the post : 

>  [VPU] Kernel binary exceeds 16KB 

OK now I understand. Well, the MYRIAD does have limited physical memory. To overcome this error please make your model smaller. 

Hope it helps,

Thanks,

Shubha

**Comment by QLSong** [comment]
@shubha-ramani 
my model is not too big.when I compile my cl to bin ,my bin is too big.I want to know if I have other method to add new op.

my cl code is as follow:
#pragma OPENCL EXTENSION cl_khr_fp16 : enable

kernel void decode(__global const half* restrict encode_box,
                   __global const half* restrict prior_box,
                   __global const half* restrict prior_var,
                   __global       half* restrict decode_box) {
    half prior_w = prior_box[2] - prior_box[0];
    half prior_h = prior_box[3] - prior_box[1];
    half prior_c_x = (prior_box[0] + prior_box[2]) / 2;
    half prior_c_y = (prior_box[1] + prior_box[3]) / 2;

    half decode_box_c_x = prior_var[0] * encode_box[0] * prior_w + prior_c_x;
    half decode_box_c_y = prior_var[1] * encode_box[1] * prior_h + prior_c_y;
    half decode_box_w = exp(prior_var[2] * encode_box[2]) * prior_w;
    half decode_box_h = exp(prior_var[3] * encode_box[3]) * prior_h;

    decode_box[0] = decode_box_c_x - decode_box_w / 2;
    decode_box[1] = decode_box_c_y - decode_box_h / 2;
    decode_box[2] = decode_box_c_x + decode_box_w / 2;
    decode_box[3] = decode_box_c_y + decode_box_h / 2;

    decode_box[0] = max(min(decode_box[0], convert_half(1)), convert_half(0));
    decode_box[1] = max(min(decode_box[1], convert_half(1)), convert_half(0));
decode_box[2] = max(min(decode_box[2], convert_half(1)), convert_half(0));
    decode_box[3] = max(min(decode_box[3], convert_half(1)), convert_half(0));
}

kernel void KernelDecodeRefineDetBoxes(
        __global const half* restrict odm_loc,
        __global const half* restrict odm_conf,
        __global const half* restrict arm_priorbox,
        __global const half* restrict arm_conf,
        __global const half* restrict arm_loc,
                       int num_classes,
                       int background_label_id,
                       float objectness_score,
        __global       half* restrict decode_box) {


    int globalid = get_global_id(0);
    int num_priors = get_global_size(0) / 4;
    int prior_index = globalid % num_priors;

    __global const half *prior_box = arm_priorbox + prior_index * 4;
 __global const half *prior_var = arm_priorbox + (num_priors + prior_index) * 4;

    odm_loc += globalid * 4, odm_conf += globalid * num_classes;
    arm_conf += globalid * 2, arm_loc += globalid * 4;
    decode_box += globalid * 6;

    decode(arm_loc, prior_box, prior_var, decode_box + 2);
    decode(odm_loc, decode_box + 2, prior_var, decode_box + 2);

    if (arm_conf[1] < objectness_score) {
        decode_box[0] = background_label_id;
        decode_box[1] = 1;
    } else {
        int max_index = -1;
        half max_score = -FLT_MAX;
        for (int c = 0; c < num_classes; ++c) {
            half score = odm_conf[c];
            if (score > max_score) {
                max_index = c;
                max_score = score;
               }
        }
        decode_box[0] = max_index;
        decode_box[1] = max_score;
    }

}

**Comment by shubha-ramani** [comment]
Dear @QLSong ,
did you carefully follow the steps on how to build a OpenCL Custom Kernel ? I'm talking about [The Inference Engine Kernels Extensibility Doc](http://docs.openvinotoolkit.org/latest/_docs_IE_DG_Integrate_your_kernels_into_IE.html).  Unfortunately, this is not really the forum for optimizing your OpenCL code to make it a smaller binary size.  [The OpenCL Optimization Guide](https://software.intel.com/en-us/iocl-opg) may help you.

Thanks,

Shubha

**Comment by shubha-ramani** [comment]
Dear @QLSong 
Just found out that there is a 32kb limit for binary size on Movidius for R3 and 16kb for R2.  This is the roof you are hitting. This should be properly documented but it's not ! Sorry about the inconvenience and the docs are being updated with this info.

Thanks,

Shubha

**Comment by geexie** [comment]
In R3 32K is a limitation for kernel binary size, which going to be removed next release. Meanwhile you could compile 2 of you kernels separate binaries or disable automatic vectorization with `-cl-auto-vectorize-disable`. It turns out that manual vectorization is usually get smaller binaries, while clc.

**Comment by QLSong** [comment]
@geexie @shubha-ramani 
Thank you very much.I have found another way to solve it.In inference-engine/src/vpu/graph_transformer/src/stages/, I add a my cpp, and I recompile it.it can be run.
