### ISSUE TITLE
cmake from inference-engine directory not build directory

### ISSUE THREAD

**Issue by peckhart89** [opencv/dldt#271]
The readme instructs to run cmake from the build directory. Running cmake from the build directory did not work. I had to run cmake from the inference-engine directory

**Comment by shubha-ramani** [comment]
Dear @peckhart89 
From [https://github.com/opencv/dldt/blob/master/inference-engine/README.md](https://github.com/opencv/dldt/blob/master/inference-engine/README.md)

the instructions read like below:

>  cmake -DCMAKE_BUILD_TYPE=Release ..

See the two little dots at the end ? This presumes that you are in the build directory. But the two dots call the CMakeLists.txt in the parent directory.

Hope it helps,

Thanks,

Shubha

**Comment by peckhart89** [comment]
Yes I did see that cmake was directed to move back a directory. I don't remember the exact error, but I think it was unable to load feature_ie. Changing directories resolved the issue for me. Thanks for responding.
