### ISSUE TITLE
cmake from inference-engine directory not build directory

### ISSUE THREAD

**Issue by zhaozj0529** [opencv/dldt#284]
https://software.intel.com/en-us/articles/intel-neural-compute-stick-2-and-open-source-openvino-toolkit

root@linaro-alip:~/dldt/inference-engine/build# cmake -DCMAKE_BUILD_TYPE=Release -DENABLE_MKL_DNN=OFF -DENABLE_CLDNN=OFF -DENABLE_GNA=OFF -DENABLE_SSE42=OFF -DTHREADING=SEQ  ..
CMake Error at CMakeLists.txt:8 (include):
  include could not find load file:
    features_ie

CMake Error at CMakeLists.txt:11 (include):
  include could not find load file:
    developer_package_ie

CMake Error at CMakeLists.txt:15 (include):
  include could not find load file:
    check_features_ie

CMake Error at CMakeLists.txt:18 (include):
  include could not find load file:
    dependencies

CMake Error at CMakeLists.txt:20 (include):
  include could not find load file:
    fuzzing

CMake Error at src/hetero_plugin/CMakeLists.txt:18 (ie_add_plugin):
  Unknown CMake command "ie_add_plugin".

CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.7)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring incomplete, errors occurred!
See also "/root/dldt/inference-engine/build/CMakeFiles/CMakeOutput.log".

**Comment by zhaozj0529** [comment]
with opencv4.1.1 python2.7.12

**Comment by ilya-lavrenov** [comment]
We moved root `CMakeLists.txt` from `dldt/inference-engine` to `dldt`. So, please use:
```
root@linaro-alip:~/dldt/inference-engine/build# cmake -DCMAKE_BUILD_TYPE=Release -DENABLE_MKL_DNN=OFF -DENABLE_CLDNN=OFF -DENABLE_GNA=OFF -DENABLE_SSE42=OFF -DTHREADING=SEQ ../..
```

**Comment by zhaozj0529** [comment]
> We moved root `CMakeLists.txt` from `dldt/inference-engine` to `dldt`. So, please use:
> 
> ```
> root@linaro-alip:~/dldt/inference-engine/build# cmake -DCMAKE_BUILD_TYPE=Release -DENABLE_MKL_DNN=OFF -DENABLE_CLDNN=OFF -DENABLE_GNA=OFF -DENABLE_SSE42=OFF -DTHREADING=SEQ ../..
> ```
Thank you very much!

**Comment by donkawechico** [comment]
The article on building openvino for arm7 could use an update to reflect the `../..` change:
https://software.intel.com/content/www/us/en/develop/articles/arm-sbc-and-ncs2.html

It still shows just the `..` which caused these errors, bringing me to this issue thread.

Should I open a new issue for this? If these articles are in a repo somewhere, I'd be happy to submit a PR making the change.

**Comment by ilya-lavrenov** [comment]
@dkurt do you know how to update that article?

**Comment by dkurt** [comment]
@ilya-lavrenov, I suggest to follow https://github.com/openvinotoolkit/openvino/wiki/BuildingForRaspbianStretchOS instead
