### ISSUE TITLE
Use Host Intel TBB

### ISSUE THREAD

**Issue by r0l1** [opencv/dldt#285]
Due to incompatibilities of the prebuild intel-tbb package on a musl (libc) based system, intel-tbb must be build with some patches. Is it possible to pass the host's intel-tbb package to cmake for the inference engine?

Kind Regards

**Comment by dkurt** [comment]
Try to specify `TBB_INCLUDE_DIRS`, `TBB_LIBRARIES_RELEASE` and `TBB_LIBRARIES_DEBUG` flags as here: https://github.com/opencv/dldt/pull/164.

**Comment by r0l1** [comment]
@dkurt perfect thank you! Worked as expected. This should be documented in the README.
