### ISSUE TITLE
Inference Engine is not working on armv6l(raspberry pi zero) 

### ISSUE THREAD

**Issue by Jishang** [opencv/dldt#287]
Hi,
Greetings.

Inference engine is not working on armv6l(raspberry pi zero). movidius myriad  is working in Google AIY Vision kit. Is there any way to build pi zero(armv6l) to run ncs2 on it?

Thanks.

From,
Jishang

**Comment by shubha-ramani** [comment]
Dearest @Jishang 

As this document [http://docs.openvinotoolkit.org/latest/_docs_install_guides_installing_openvino_raspbian.html](http://docs.openvinotoolkit.org/latest/_docs_install_guides_installing_openvino_raspbian.html) says:

> Raspberry Pi* board with ARM* ARMv7-A CPU architecture. Check that uname -m returns armv7l.

So unfortunately armv6l is not supported.

Sorry for the inconvenience.

Shubha

**Comment by Jishang** [comment]
But the NCS support the previous version is working with the armv6l  is working with NCS. Also Myriad 2 is working with pi zero (armv6l) For reference,
https://forums.intel.com/s/question/0D50P00004NM07T/45-raspberry-pi-zero-w-hat-with-a-movidius-myriad-2-vpu?language=en_US .
Please look into these also.

**Comment by shubha-ramani** [comment]
Dear @Jishang 
That was from 2 years ago though. 
You can still make it work but you'd have to build OpenCV and Inference Engine from scratch and fix errors as you go along. All the source code is available in the dldt github repo, to enable you do this.

Hope it helps.

Thanks,

Shubha

**Comment by Jishang** [comment]
> at was from 2 years ago though.
> You can still make it work but you'd have to build OpenCV and Inference Engine from scratch and fix errors as you go along. All the source code is available in the dldt github repo, to enable you do this.
> 
> Hope it helps.
> 
> Thanks,
> 
> Shubha

i tried and its working. thank from scratc i hae to build every thing. Thanks for the info

**Comment by jacopomaroli** [comment]
Since this issue is not so old and it's one of the first hits when you search for Openvino on RPi0 I'll post this here:
I had the same need, so since it wasn't a trivial procedure I shared the notes I collected during the process https://github.com/jacopomaroli/intel-neural-compute-stick-2-raspberry-pi-zero

This will guide you into building qemu/openCV/inference engine for RPi zero
