### ISSUE TITLE
Support of pip/wheel package

### ISSUE THREAD

**Issue by masamitsu-murase** [opencv/dldt#292]
First of all, let me say thank you for this great software!

I have 2 questions about pip package of OpenVINO.

* Does the community have a plan to support a python pip/wheel package for OpenVINO?
  Currently, I couldn't find a pip/wheel package for OpenVINO though Intel-numpy and other packages are registered in PyPI.
  I would like to know whether the community has a plan to release it in the future.
* Can I publish a pip/wheel package for OpenVINO?
  I have created a wheel package of OpenVINO for my personal use, but I'm not sure whether I can publish it in PyPI or on my own web page.
  If I should not publish it, please let me know.

Again, thank you very much for the great software!

Regards,
Murase

**Comment by antonrom23** [comment]
Dear @masamitsu-murase ,
About the first question. Yes, the community have a plan to support a python pip package for OpenVINO in the future.
About the second question, yes , you can publish in your own web page. And it will be very great, if you provide instructions on how  you create pip/wheel package of OpenVino. This will help us enable pip package more faster.

**Comment by masamitsu-murase** [comment]
Thank you very much for your reply.
I understood the current status.

I will publish the pip package in the following repositories soon.
* https://github.com/masamitsu-murase/openvino-python
* https://github.com/masamitsu-murase/openvino-rt

Regards,
Murase

**Comment by masamitsu-murase** [comment]
@antonrom23 
This is just for your information.
I comitted changesets to create a pip package for OpenVINO on Windows in the following repository.
  https://github.com/masamitsu-murase/openvino-python

`setup.py` has some changes to include prebuilt `*.pyd` files in the pip package.
I hope this implementation helps you in the future.

Regards,
Murase
