### ISSUE TITLE
Python result is not same as C++

### ISSUE THREAD

**Issue by xiaoweiChen** [opencv/dldt#311]
I have a OpenVINO crnn example form https://github.com/FionaZZ92/OpenVINO/tree/master/CRNN.

I convert the pytorch model to onnx, and make onnx to OpenVINO .bin and .xml.

Use `cpu_extension_avx2.dll`(Compiled) and `cpu_extension.dll`(Build Samples generated) py openvino_2019.3.379, the python example running well. 

The Result like below:
```
python openvino_crnn_demo.py -m ./crnn-openvino/crnn.xml -i ./test_img/image_data2.npy -d CPU -l cpu_extension.dll
args.cpu_extension is cpu_extension.dll
[ INFO ] Loading network files:
        ./crnn-openvino/crnn.xml
        ./crnn-openvino/crnn.bin
[ INFO ] Preparing input blobs
input shape [1, 1, 37, 100]
image len 3700
resized image shape (1, 1, 37, 100)

[ INFO ] Batch size is 1
[ INFO ] Loading model to the plugin
[ INFO ] Starting inference (1 iterations)
[ INFO ] Average running time of one iteration: 33.002376556396484 ms
[ INFO ] Processing output blob
[ INFO ] Top 10 results:
(26, 1, 37)
res is [[[-107.36757  -116.02504  -114.33578  -114.94623  -117.209045
   -114.108444 -116.2726   -115.52344  -116.09996  -115.33161
   -114.69289   -89.02753  -109.611145 -110.2062   -106.49509
   -106.193    -109.85676  -109.10684  -111.73262  -105.31891
   -108.81292  -112.97046  -107.483055 -107.55609  -107.61348
   -105.423935 -107.74873  -113.45503  -107.92154  -107.58439
   -110.036964 -106.533325 -107.905136 -108.19947  -113.58542
   -109.56166  -113.45506 ]]
 ...
 [[ -60.164463  -87.596146  -86.182205  -87.89369   -85.67219
    -86.80545   -85.39952   -87.77957   -88.10416   -87.47627
    -88.25757   -78.12369   -80.36737   -80.60395   -77.651726
    -78.78531   -79.46525   -81.929535  -80.84323   -78.851234
    -83.00974   -81.64218   -76.87636   -78.618675  -80.34229
    -78.50218   -77.81128   -85.64299   -78.15444   -75.33519
    -76.93544   -80.0434    -78.790375  -81.012054  -82.55629
    -77.33411   -79.85093 ]]]

[[11.  0.  0.  0.  0.  0. 32.  0.  0. 11.  0. 19.  0. 22.  0. 11.  0. 12.
   0.  0. 22.  0. 15.  0.  0.  0.]]
lalphabet len 37
a     v  a i l a b  l e
```

Well, I want tranfrom this example to C++, and change the `hello_classification` example.
But I get error result:
```
        CPU
        MKLDNNPlugin version ......... 2.1
        Build ........... 32974

input shape[1, 1, 37, 100]
output size is 962
15
36
0
36
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
17
0
This sample is an API example, for any performance measurements please use the dedicated benchmark_app tool
```

The C++ code in the zip:
[c++code.zip](https://github.com/opencv/dldt/files/3787295/c%2B%2Bcode.zip)

I use python example generate image.raw which used in c++ code.
```python
...
        import struct
        with open('image.raw', 'wb')as fp:
          for x in image.flatten():
            a = struct.pack('f', x)
            fp.write(a)
...
```
[openvino_crnn_demo.zip](https://github.com/opencv/dldt/files/3787299/openvino_crnn_demo.zip)

Hope someone can help me.

**Comment by xiaoweiChen** [comment]
Under Linux, the result is same as python version.

**Comment by maozhong1** [comment]
so you solve this issue on linux?(c++ have same result as python in linux)  @xiaoweiChen

**Comment by xiaoweiChen** [comment]
@maozhong1  Right. Under Linux, Use the same code, this issue is not reproduce and can get rigth result. 
But result not stable, executing multiple times in succession, I get different result in same program.
I tested Opensource and Release binary 2019 R3.1 version.

Like below: ("a     v  a i l a b  l e  " is expected)
```
(base) $ ./crnn crnn.xml image.raw ${INTEL_CVSDK_DIR}/deployment_tools/inference_engine/lib/intel64/libcpu_extension_sse4.so
InferenceEngine: 
	API version ............ 2.1
	Build .................. custom_releases/2019/R3_cb6cad9663aea3d282e0e8b3e0bf359df665d5d0
	Description ....... API
	CPU
	MKLDNNPlugin version ......... 2.1
	Build ........... 30677

input shape[1, 1, 37, 100]
output size is 962
a     v  a i l a b  l e   
(base) $ ./crnn crnn.xml image.raw ${INTEL_CVSDK_DIR}/deployment_tools/inference_engine/lib/intel64/libcpu_extension_sse4.so
InferenceEngine: 
	API version ............ 2.1
	Build .................. custom_releases/2019/R3_cb6cad9663aea3d282e0e8b3e0bf359df665d5d0
	Description ....... API
	CPU
	MKLDNNPlugin version ......... 2.1
	Build ........... 30677

input shape[1, 1, 37, 100]
output size is 962
eczo 77  a i   a bb l e   

(base) $ ./crnn crnn.xml image.raw ${INTEL_CVSDK_DIR}/deployment_tools/inference_engine/lib/intel64/libcpu_extension_sse4.so
InferenceEngine: 
	API version ............ 2.1
	Build .................. custom_releases/2019/R3_cb6cad9663aea3d282e0e8b3e0bf359df665d5d0
	Description ....... API
	CPU
	MKLDNNPlugin version ......... 2.1
	Build ........... 30677

input shape[1, 1, 37, 100]
output size is 962
 ez    v a i   a bb l e   
```

OpenSource version 2019 R3,1 OpenVINO have some compiling error under Windows which I have no idea to fix right now. So just test Release Version under Windows.

**Comment by xiaoweiChen** [comment]
put this [crnn.zip](https://github.com/opencv/dldt/files/3812552/crnn.zip) to `sample` dir, then cmake and make.
You can get the result like above.

**Comment by xiaoweiChen** [comment]
put this [crnn.zip](https://github.com/opencv/dldt/files/3812552/crnn.zip) to `sample` dir, then cmake and make.
You can get the result like above.

**Comment by liyong4x** [comment]
@xiaoweiChen How can I get the pytorch model crnn.xml and crnn.bin?

**Comment by xiaoweiChen** [comment]
@liyong4x 
Openvino not support pytorch convert to IR. 
Pytorch model should convert to onnx, you can reference here https://github.com/FionaZZ92/OpenVINO/tree/master/CRNN, the `pytorch2onnx` would be help you knowing more detail for pytorch to onnx.

**Comment by liyong4x** [comment]
Could you upload you crnn.bin?  Only find crnn.xml in c++code.zip.

**Comment by xiaoweiChen** [comment]
The maximum package size is 10M which Github supported.
You can find the donwload url from here https://github.com/meijieru/crnn.pytorch

**Comment by maozhong1** [comment]
@xiaoweiChen , would you kindly share us the same bin/xml file(baidu pan or other approach) , we try to reproduce it and do debug.  thanks!

**Comment by xiaoweiChen** [comment]
En... I can upload xml and bin tonight. When finish upload, I will share the download address here.

If the time is too late, you can get the model form https://github.com/meijieru/crnn.pytorch, and convert it to onnx, then to OpenVINO IR(xml/bin).  Try to reproduce the issue.

**Comment by maozhong1** [comment]
@xiaoweiChen  we have converted trained model to IR and can duplicate this issue. Python result is OK. C++ result in Ubuntu is not consistent.

**Comment by xiaoweiChen** [comment]
@maozhong1
Yeap, same with mine. Python is alway OK, C++ is not under Linux(I test on Centos 7 and Ubuntu 16.04).
This result is stranged for me, because the pulgin and extension library is same, but get different result.
Even, C++ can not get Wrong result under Windows(10).

**Comment by maozhong1** [comment]
@xiaoweiChen , I root caused this issue. in your c++ code，rawData is dynamically allocated and it will pass to input Blob by function "make_shared_blob". in some case ,the memory is automatically released.
std::unique_ptr<float[]> rawData(new float[input_size]);
if I used static float array or move the above line out from the inline function.  C++ will always generate same result as python. refer to attached main.cpp file

**Comment by maozhong1** [comment]
attached main.cpp

[main.zip](https://github.com/opencv/dldt/files/3834494/main.zip)

**Comment by xiaoweiChen** [comment]
Thank you for @maozhong1 
I test your code on my platforms(ubuntu 16.04 and windows 10). The code work well. :)
I can continue do the crnn reasearching on OpenVINO now.

**Comment by oms291** [comment]
Hi,
I'm still struggling to get the same result in c++ as python in windows 10 with OpenVINO 2020.3 or 2021.2 version.
I checked the same result using openvino python api in python with onnx file and IR files.
I also tried using std::unique_ptr<float[]> as static float array but it didn't work.
i'm using object_detection_sample_ssd. 

Is there any suggestion?

Thanks.
