### ISSUE TITLE
Human pose estimation with MYRIAD not work

### ISSUE THREAD

**Issue by whatisor** [opencv/dldt#315]
I am running 2019 R1 version with NCS2, I can run security sample with MYRIAD.
 However, pose estimation demo never finish to loading model

>  C:\Users\xxxxxxxx\Documents\Intel\OpenVINO\inference_engine_samples_build\intel64\Release> .\human_pose_estimation_demo.exe -d MYRIAD -m .\human-pose-estimation-0001.xml -i .\pose_1.bmp -r
> InferenceEngine:
>         API version ............ 1.6
>         Build .................. 23780
> [ INFO ] Parsing input parameters
> 

It keeps loading forever.

If I use GPU device, loading time is also big but it can complete for a few seconds.

**Comment by whatisor** [comment]
Note: I used FP16 models.

**Comment by ArtemSkrebkov** [comment]
Looks like this model is not supported for MYRIAD platform in 2019 R1 release. Please take a look at the table with supported models for R1 release.
https://github.com/opencv/open_model_zoo/blob/e4d1e85b3ed42372ce3514b98a15f51da94387d6/demos/README.md
Have you tried the latest release? According to the table https://github.com/opencv/open_model_zoo/blob/4e3dbe1de2377d826018c67fd0989e28614229a3/demos/README.md the models is supported now.

**Comment by whatisor** [comment]
Thank @ArtemSkrebkov , it works with the latest version.
