### ISSUE TITLE
Age gender model to int8 format

### ISSUE THREAD

**Issue by NikolaMr** [opencv/dldt#319]
Hi!

I am trying to convert the age-gender model (http://docs.openvinotoolkit.org/latest/_models_intel_age_gender_recognition_retail_0013_description_age_gender_recognition_retail_0013.html) to INT8 format. However, the model I get as the output of calibrate.py script is about the same size as the FP32 model (xml file is even bigger for the int8 version). Plus, when I try to set the weights to the model using the `network_reader.SetWeights(weightsPtr);` I get `segment exceeds given buffer limits. Please, validate weights file` error.

My question is, how to perform appropriate int8 conversion?

Is my premise that the INT8 model should be the quarter size of the FP32 model correct?
In conjunction with the calibrate.py's -sm option I am also using -cfc option to convert even the fully connected layers to INT8 but it doesn't seem to have an effect.

Thanks in advance for the help!

**Comment by YijinLiu** [comment]
I have the same problem. It seems to me the latest IR doesn't accept models converted by old versions of the software. The same model works for me with R1.1, not with R3.
However, R1.1 won't accept a model converted by R3 either. This is nightmare for software deployment.. Hope there is a solution to this.

**Comment by NikolaMr** [comment]
I have this problem even when I generate IR for my model with the R3 version of the model optimizer tool and then apply the calibration tool so I don't think it is related to the software version being mismatched between the models.

**Comment by elvin-nnov** [comment]
IR which are targeted for execution in int8 mode still have floating point weights and rules (implicit so far) how to quantize them. Model is transformed for int8 execution in runtime and weights are quantized.
Regarding the age gender - i am not sure if this model can be currently calibrated and even if it can calibrated, there would be any perf gain from int8. This model is very fast evan in fp32 mode.

As for `segment exceeds given buffer limits. Please, validate weights file` error - `ICNNNetReader::SetWeights` accepts weights which already are loaded to the memory. Why did not you use `ICNNNetReader::ReadWeights` and what are the weights which tyou feed to `ICNNNetReader::SetWeights`?

**Comment by NikolaMr** [comment]
Interesting, I thought that this would be the case. 
How come that it isn't saved as int8 instead of transforming it in runtime?

Regarding the error, the problem was that I was using the `.lib` file for `inference_engine` from an older version while the `.dll` was for an R3.1 version. After setting the same versions for both the `.lib` and `.dll` the problem disappeared.
