### ISSUE TITLE
 Hyperlink of  OpenVINO™ pre-trained models returns 404.

### ISSUE THREAD

**Issue by yuanliya** [opencv/dldt#321]
On page https://github.com/opencv/dldt/blob/2019/get-started-linux.md ， the hyperlink of  OpenVINO™ pre-trained models doesn't work and returns the error code 404 . I successfully found the model zoo folder, but I think it may be better to update the hyperlink :D.

**Comment by asuhov** [comment]
Fixed, thank you!
