### ISSUE TITLE
How to make async code for two different model using OpenVINO?

### ISSUE THREAD

**Issue by nehasoni3** [opencv/dldt#337]
Hi Techies
I am working on neural network optimization using OpenVINO toolkit.
I have two model.
output of first model is the input of second model.

I have write async inferencing code for first model.
When I tried to write async inferencing code for second model, it shows error i.e 

> Request Busy

Can it possible to run 2 model async using OpenVINO.
If it is, Please help me to get out of this error.

Thanks

Looking for response.

**Comment by elvin-nnov** [comment]
Definitely it is possible. For example you can evaluate https://github.com/opencv/open_model_zoo/tree/master/demos/security_barrier_camera_demo which might run three networks in parallel for several streams.
Some questions
- Is the output of the first goes directly t the second?
- Do you use callbacks or wait() to get results?
- What device do you use?

**Comment by nehasoni3** [comment]
> Definitely it is possible. For example you can evaluate https://github.com/opencv/open_model_zoo/tree/master/demos/security_barrier_camera_demo which might run three networks in parallel for several streams.
> Some questions
> 
> * Is the output of the first goes directly t the second?
> * Do you use callbacks or wait() to get results?
> * What device do you use?

Hi @elvin-nnov 

This is C++ demo. It is bit difficult to understand the flow of code.
1. Yes, first model is object detection model, the detected object image passes to another model.
2. Yes, I have used
3. I am working on Desktop (Intels XEON)

I have followed  **object_detection_demo_ssd_async.py** . It uses single model for async inferencing.

It will be more helpful for me if sample code of multiple async inferencing code is in PYTHON.

Thanks.

**Comment by elvin-nnov** [comment]
Here is a python demo having several networks: https://github.com/opencv/open_model_zoo/tree/master/demos/python_demos/face_recognition_demo

**Comment by nehasoni3** [comment]
thanks @elvin-nnov
