### ISSUE TITLE
undefined reference in OpenVino linux integration

### ISSUE THREAD

**Issue by dimitryn** [opencv/dldt#345]
Hi , I am trying to integrate openVino into our MW on Linux. Official OpenVino installation or compiled from sources create a same error when I link openVino libraries into out MW.

undefined reference to `InferenceEngine::Data::getName[abi:cxx11]() const'
undefined reference to `InferenceEngine::Core::Core(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
XXXX..so: undefined reference to `InferenceEngine::Core::LoadNetwork(InferenceEngine::CNNNetwork, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&)'
collect2: error: ld returned 1 exit status

this list of libraries when compiling opeVino I use 

	set(OPEN_VINO_LIB 				
		${OPEN_VINO_DIR}/x86_64/libclDNNPlugin.so
		${OPEN_VINO_DIR}/x86_64/libcpu_extension.so
		${OPEN_VINO_DIR}/x86_64/libinference_engine.so 
		${OPEN_VINO_DIR}/x86_64/libMKLDNNPlugin.so
		${OPEN_VINO_DIR}/x86_64/libtbb.so.2
		${OPEN_VINO_DIR}/x86_64/libtbbmalloc.so.2

Please Advise what steps should I do to  work with OpenVino on Linux.

**Comment by brmarkus** [comment]
Are you sure you have set the library search path correctly (e.g. `source /opt/intel/openvino/bin/setupvars.sh`)?
The library "libinference_engine.so is below `/opt/intel/openvino/inference_engine/lib/intel64`.

When I run `strings /opt/intel/openvino/inference_engine/lib/intel64/libinference_engine.so | grep "Core"` then I can see the symbols your linker claims to have missing..., e.g.:

`_ZN15InferenceEngine4Core11LoadNetworkENS_10CNNNetworkERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKSt3mapIS7_S7_St4lessIS7_ESaISt4pairIS8_S7_EEE`

Have you enabled "cx11" or "cx14" for your compiler, e.g. in CMakeLists.txt via `set (CMAKE_CXX_FLAGS "-std=c++11 ${CMAKE_CXX_FLAGS}")` ?

**Comment by dimitryn** [comment]
@brmarkus 
1.Yes ,  all missing string exists in so. but if you run >nm libinference_engine.so you getting no symbols?!!!
2. I don't want to use setupvars.sh . Our MW will be installed on many machines and I only need necessary shared libraries from OpenVino.

**Comment by brmarkus** [comment]
Ok, you don't need to source `setupvars.sh`, you could only extract the relevant parts like setting LD_LIBARY_PATH and such.

Can you maybe share the linker command line from your build log? This command line should contain the name of the library/libraries the linker should use (´inference_engine´, will be expanded to libinference_engine.so or libinference_engine.a) and the library search path. Are you sure the linker is looking for the library at the correct place in your file system?

Are you using C++11 or C++14? Maybe you have missed to set c++11, which impacts the name-mangling of symbol names.

**Comment by brmarkus** [comment]
The man-page "https://www.systutorials.com/docs/linux/man/1-nm/" says:

> GNU nm lists the symbols from object files objfile.... If no object files are listed as arguments, nm assumes the file a.out.

But "libinference_engine.so" is not a (static) "object file"...

**Comment by dimitryn** [comment]
@brmarkus yes  you right.  it should be >nm -D. now it works. I need to check linkage
