### ISSUE TITLE
INT8 model with (depthwise convolution + leaky ReLU) is very slow

### ISSUE THREAD

**Issue by car1hsiung** [opencv/dldt#356]
Hi,

I found some INT8 model contains depthwise convolution is very slow (slow than FP32), e.g. person-detection-retail-0013, INT8 [xml](https://download.01.org/opencv/2019/open_model_zoo/R3/20190905_163000_models_bin/person-detection-retail-0013/INT8/person-detection-retail-0013.xml) and [bin](https://download.01.org/opencv/2019/open_model_zoo/R3/20190905_163000_models_bin/person-detection-retail-0013/INT8/person-detection-retail-0013.bin), also FP32: [xml](https://download.01.org/opencv/2019/open_model_zoo/R3/20190905_163000_models_bin/person-detection-retail-0013/FP32/person-detection-retail-0013.xml) and [bin](https://download.01.org/opencv/2019/open_model_zoo/R3/20190905_163000_models_bin/person-detection-retail-0013/FP32/person-detection-retail-0013.bin)

If you use `benchmark_app` built from `openvino/deployment_tools/inference_engine/samples`

```
./benchmark_app -m person-detection-retail-0013_i8.xml -d CPU -api sync -pc -niter 10
```

You can see begin of log:
```
data_nchw_nhwc_mbox1/priorbox NOT_RUN        layerType: Reorder            realTime: 0         cpu: 0               execType: jit_uni_I8
data_U8_FP32_Mul_12401/Fus... EXECUTED       layerType: Reorder            realTime: 63        cpu: 63              execType: jit_uni_I8
Mul_12401/Fused_Mul_/Fused... EXECUTED       layerType: ScaleShift         realTime: 89        cpu: 89              execType: jit_avx2_FP32
Mul_12401/Fused_Mul_/Fused... EXECUTED       layerType: Reorder            realTime: 91        cpu: 91              execType: jit_uni_FP32
init_block1/dim_inc/conv      EXECUTED       layerType: Convolution        realTime: 244       cpu: 244             execType: jit_avx2_I8
init_block1/dim_inc/fn        NOT_RUN        layerType: ReLU               realTime: 0         cpu: 0               execType: undef
bottleneck1_1/dim_red/conv    EXECUTED       layerType: Convolution        realTime: 63        cpu: 63              execType: jit_avx2_I8
bottleneck1_1/dim_red/fn      NOT_RUN        layerType: ReLU               realTime: 0         cpu: 0               execType: undef
bottleneck1_1/inner/dw1/conv  EXECUTED       layerType: Convolution        realTime: 1753      cpu: 1753            execType: gemm_blas_I8
```

the last of line, `bottleneck1_1/inner/dw1/conv` is `gemm_blas_I8`, whereas FP32 is `jit_avx2_dw_FP32`.

```
bottleneck1_1/inner/dw1/conv  EXECUTED       layerType: Convolution        realTime: 51        cpu: 51              execType: jit_avx2_dw_FP32
```

But [ssdlite_mobilenet_v2](http://download.tensorflow.org/models/object_detection/ssdlite_mobilenet_v2_coco_2018_05_09.tar.gz) is work.

```
FeatureExtractor/Mobilenet... EXECUTED       layerType: Convolution        realTime: 192       cpu: 192             execType: jit_avx2_dw_I8
```

(converted by following commands:)

```
python3 ./mo_tf.py \
--input_model frozen_inference_graph.pb \
--tensorflow_object_detection_api_pipeline_config pipeline.config \
--input_shape [1,300,300,3] \
--tensorflow_use_custom_operations_config /path/to/openvino/deployment_tools/model_optimizer/extensions/front/tf/ssd_v2_support.json
```

and

```
python3 calibrate.py -sm -td CPU \
-e /path/to/openvino/inference_engine/lib/intel64/libcpu_extension_sse4.so \
-m frozen_inference_graph.xml
```

I found ReLu type is different between `person-detection-retail-0013` and `ssdlite_mobilenet_v2`.
If you delete all of `<data negative_slope="0.100000" />` lines in person-detection-retail-0013_i8.xml, than run benchmark_app again, `gemm_blas_I8` will be instead of `jit_avx2_I8` and FPS of INT8 will be faster than FP32.

Do I miss something, or is it a bug?

Environment:

```
CPU I7-7700
Ubuntu 1604
OpenVINO 2019 R3
```

Thanks

**Comment by NikolaMr** [comment]
@elvin-nnov or @shubha-ramani, could you be able to detect the problem that causes the slow-down with the INT8 quantized model compared to the FP32 model?

**Comment by yury-gorbachev** [comment]
That will be fixed in next release - it is runtime issue.
