### ISSUE TITLE
How do you build inference engine dll in such a way all its dependencies are in one folder? In other words, I won't need to run setupvars.bat everytime I want to use the dll...

### ISSUE THREAD

**Issue by mmbajo** [opencv/dldt#376]
As per the title, I would like to build a dll that don't need to run the setupvarsbat before the dll can be used. Is this possible??

**Comment by mmbajo** [comment]
As per the title, I would like to build a dll that don't need to run the setupvarsbat before the dll can be used. Is this possible??

**Comment by dkurt** [comment]
It's mostly generic Windows development question. Try to find information, how to specify paths to linked shared libraries in Windows. You may do it with environment variables. So the same is done by setupvars automatically.

**Comment by mmbajo** [comment]
Thank you very much!! I am sorry for posting such a noob question! Now I can use the dll without setupvars.bat by setting them manually in the env variables!
