### ISSUE TITLE
'-ni' and '-nireq' classification_sample_async options are failing.

### ISSUE THREAD

**Issue by Ferhdez** [opencv/dldt#381]
**SUMMARY**
When using -ni and -nireq classifitaion_sample_async options with hyphens the applications come back with following error:
ERROR: unknown command line flag 'ni'
ERROR: unknown command line flag 'nireq'

**STEPS TO REPRODUCE:**
* get wget, which, computer-vision-basic
   "swupd bundle-add wget which computer-vision-basic"

* get car image
   "wget https://docs.seldon.io/projects/seldon-core/en/latest/_images/car.png" 

* get model_zoo_dir resnet-50 downlader
   "/cntr_workdir/open_model_zoo/model_downloader/downloader.py -o /cntr_workdir --name resnet-50"

* Convert a Caffe* Model to produce an optimized Intermediate Representation (IR) of the model based on the trained network topology, weights, and biases values
   "python /usr/share/openvino/model-optimizer/mo_caffe.py --data_type=FP32 --input_shape=[1,3,224,224] --mean_values=data[104.0,117.0,123.0] --output=prob --input_model=resnet-50.caffemodel --input_proto=resnet-50.prototxt"
[ SUCCESS ] Generated IR model.
[ SUCCESS ] XML file: /cntr_workdir/classification/resnet/v1/50/caffe/./resnet-50.xml
[ SUCCESS ] BIN file: /cntr_workdir/classification/resnet/v1/50/caffe/./resnet-50.bin
[ SUCCESS ] Total execution time: 25.00 seconds.   

* Test the model in the IR format using the Inference Engine in the target environment via provided Inference Engine validation application.
root@fabddfe81ca3/workspace # classification_sample_async -i /cntr_workdir/car.png -m /cntr_workdir/classification/resnet/v1/50/caffe/resnet-50.xml -ni 100 -nireq 4
[ INFO ] InferenceEngine:
        API version ............ 2.0
        Build .................. custom__
        Description ....... API
[ INFO ] Parsing input parameters
ERROR: unknown command line flag 'ni'
ERROR: unknown command line flag 'nireq'

**EXPECTED RESULT**
Able to run the classification_sample_async application with '-ni' '-nireq' Options
   "classification_sample_async -i /cntr_workdir/image_infer_t.jpeg -m /cntr_workdir/classification/resnet/v1/50/caffe/resnet-50.xml -ni 100 -nireq 4"
[ INFO ] InferenceEngine:
        API version ............ 2.0
        Build .................. custom__
        Description ....... API
[ INFO ] Parsing input parameters
[ INFO ] Parsing input parameters
[ INFO ] Files were added: 1
[ INFO ]     /cntr_workdir/car.png
[ INFO ] Creating Inference Engine
        CPU
        MKLDNNPlugin version ......... 2.1
        Build ........... custom_v2019_R3.1_fe3f978b98c86eaeed3cbdc280e1ffd0bc50d278

[ INFO ] Loading network files
[ INFO ] Preparing input blobs
[ WARNING ] Image is resized from (787, 259) to (224, 224)
[ INFO ] Batch size is 1
[ INFO ] Loading model to the device
[ INFO ] Create infer request
[ INFO ] Start inference (10 asynchronous executions)
[ INFO ] Completed 1 async request execution
[ INFO ] Completed 2 async request execution
[ INFO ] Completed 3 async request execution
[ INFO ] Completed 4 async request execution
[ INFO ] Completed 5 async request execution
[ INFO ] Completed 6 async request execution
[ INFO ] Completed 7 async request execution
[ INFO ] Completed 8 async request execution
[ INFO ] Completed 9 async request execution
[ INFO ] Completed 10 async request execution
[ INFO ] Processing output blobs

Top 10 results:

Image /cntr_workdir/car.png

classid probability
------- -----------
717     0.3228686
817     0.1538750
581     0.1423150
479     0.0849617
436     0.0527374
468     0.0428489
705     0.0232187
511     0.0191299
751     0.0189609
704     0.0109762

**ACTUAL RESULT**
Classification_sample_async app failing when using hypens options.
root@fabddfe81ca3/workspace # classification_sample_async -i /cntr_workdir/car.png -m /cntr_workdir/classification/resnet/v1/50/caffe/resnet-50.xml -ni 100 -nireq 4
[ INFO ] InferenceEngine:
        API version ............ 2.0
        Build .................. custom__
        Description ....... API
[ INFO ] Parsing input parameters
ERROR: unknown command line flag 'ni'
ERROR: unknown command line flag 'nireq'

**Comment by jgespino** [comment]
Hi @Ferhdez 

The latest Image Classifications Sample Async does not include the -ni & -nireq options. Take a look at the [README page](https://docs.openvinotoolkit.org/latest/_inference_engine_samples_classification_sample_async_README.html). You can print the app help message with the -h option.

Regards,
Jesus

**Comment by Ferhdez** [comment]
Many thanks for update the official documentation, I will close this issue.
