### ISSUE TITLE
Inference Engine C++ API and faster_rcnn_resnet1010_coco inputblob dim not correct

### ISSUE THREAD

**Issue by qiyuangong** [opencv/dldt#393]
Hi,
     I have an OpenVINO faster_rcnn_resnet1010_coco model from OpenVINO 2019_R3 model zoo. I'm trying to load and predict with Inference Engine C++ API of OpenVINO 2020_R1. 

Network read is successful. But data dim of inputblob is [1, 3], rather than [1, 3, 600, 600]. Why? and how to solve this problem?

**Comment by jgespino** [comment]
Hi @qiyuangong 

The converted model has an image_tensor with shape [1x3x600x1024] and an image_info with shape [1x3]. You can find additional details in the [model documentation](https://github.com/opencv/open_model_zoo/blob/master/models/public/faster_rcnn_resnet101_coco/faster_rcnn_resnet101_coco.md). 

_Input Name: image_info
Input shape [1, 3]
Input Name: image_tensor
Input shape [1, 3, 600, 1024]_

Take a look at the [L219](https://github.com/opencv/open_model_zoo/blob/master/demos/object_detection_demo_faster_rcnn/main.cpp#L219) of the Object Detection Demo Faster RCNN on how to implement.

When converting the model, you need to specify  the image_tensor as the input with the following command.

`python3 /opt/intel/openvino/deployment_tools/model_optimizer/mo.py \`
`--reverse_input_channels \`
`--input_shape=[1,600,1024,3] \`
`--input=image_tensor \`
`--output=detection_scores,detection_boxes,num_detections \`
`--transformations_config=/opt/intel/openvino/deployment_tools/model_optimizer/extensions/front/tf/faster_rcnn_support.json \`
`--tensorflow_object_detection_api_pipeline_config=pipeline.config \`
`--input_model=frozen_inference_graph.pb`

Regards,
Jesus

**Comment by qiyuangong** [comment]
Hi @jgespino 

Thank you for quick reply. :) I will try this method. 

Qiyuan

**Comment by qiyuangong** [comment]
Another question about this model. 

If this model is already converted with 2 input, i.e., image_info and image_tensor.

Can I correctly predict with them using this example code (https://github.com/opencv/dldt/blob/2020/inference-engine/samples/object_detection_sample_ssd/main.cpp#L140) ?

**Comment by jgespino** [comment]
Hi @qiyuangong 

Yes, the object detection sample ssd should work with this model.
Give it a try!

Regards,
Jesus

**Comment by qiyuangong** [comment]
Hi @jgespino 

I tried this example code. It works for both image classification and object detection! Thank you! 

 I think maybe you can add some doc or comments about this difference. :)

Regards,
Qiyuan

**Comment by qiyuangong** [comment]
Issue closed. :)
