### ISSUE TITLE
Building on Ubuntu 19.04 with a few modification

### ISSUE THREAD

**Issue by qiyuangong** [opencv/dldt#400]
I know Ubuntu 19.04 is not listed in supported OS. But, some customers do have desktops or servers with Ubuntu 19.04.  

I found that building is stacked by downloading OS related files.  So, I made some modification on `dependencies.cmake`, and make it works. :)

Insert these lines into https://github.com/opencv/dldt/blob/2020/inference-engine/cmake/dependencies.cmake#L150 .

```cmake
        elseif (${LINUX_OS_NAME} STREQUAL "Ubuntu 19.04")
            set(OPENCV_SUFFIX "ubuntu18")
        endif()
```
After this change, cmake will download files for Ubuntu 18.04, and make building successful. :)

**Comment by jgespino** [comment]
@qiyuangong Thanks for sharing!

**Comment by qiyuangong** [comment]
Issue closed. :)
