### ISSUE TITLE
Offloading Sub-Graph Inference to TensorFlow*

### ISSUE THREAD

**Issue by DucLong06** [opencv/dldt#405]
offload subgraph inference for TensorFlow *?
I am trying to offload the Mobilenet V2 1.0 224 model download from: https://docs.openvinotoolkit.org/latest/_docs_MO_DG_prepare_model_convert_model_Convert_Model_From_TensorFlow.html
but when i run build.sh file in tf_call_ie_layer encountered an error :
lerror @ LTOL: / opt / intel / openvino / bin $ ./setupvars.sh
[setupvars.sh] OpenVINO environment initialized
lerror @ LTOL: / opt / intel / openvino / bin $ cd '/ opt / intel / openvino / deployment_tools / model_optimizer / tf_call_ie_layer'
lerror @ LTOL: / opt / intel / openvino / deployment_tools / model_optimizer / tf_call_ie_layer $ ./build.sh
ERROR: INTEL_OPENVINO_DIR environment variable is not set
Please, run the 'source <OpenVINO_install_dir> /bin/setupvars.sh'
Although I've already initialized an environment variable, it still doesn't work. Can you guys please help me?

**Comment by jgespino** [comment]
Hi @DucLong06,

Thanks for reaching out. Is there a particular reason why you need to offload sub-graph to tensorflow for this model? The model is listed as a supported model from TensorFlow Lite, you can continue to convert to IR format for inference.

`source /opt/intel/openvino/bin/setupvars.sh`

`python3 /opt/intel/openvino/deployment_tools/model_optimizer/mo.py --framework tf --input_model mobilenet_v2_1.0_224_quant_frozen.pb --batch 1 --reverse_input_channels --output output --input input`

Regards,
Jesus

**Comment by DucLong06** [comment]
yes thank you. So which models need to convert. I am also wondering about the problem of freezing:
https://docs.openvinotoolkit.org/latest/_docs_MO_DG_prepare_model_convert_model_Convert_Model_From_TensorFlow.html
Can you explain for me please. thank you

**Comment by jgespino** [comment]
Hi @DucLong06 

I noticed you started a new issue. If it's okay with you, let's close this issue and continue to work on #409 .

Regards,
Jesus
