### ISSUE TITLE
IPP renew?

### ISSUE THREAD

**Issue by jiapei100** [opencv/dldt#406]
Hi, Intel tech support:

It seems [https://software.seek.intel.com/performance-libraries](https://software.seek.intel.com/performance-libraries) wouldn't show in HTML5 with CSS. That is to tell my 1-year license with IPP is over ?

Is there a way to renew IPP free license?
Otherwise, is there a way to build ideep/dldt etc. without IPP?

Thank you very much
Pei.

**Comment by alalek** [comment]
Duplicate of #312
Disable "uBlock" or similar browser extension for this site.

Why do you think that DLDT requires IPP?

**Comment by jiapei100** [comment]
@alalek 

Thank you ... That solved my issue. Thanks....
