### ISSUE TITLE
Where is dldt/inference-engine/README for 2020?

### ISSUE THREAD

**Issue by banderlog** [opencv/dldt#420]
Hi, there was an excellent README.md in 2019 branch, 2020 branch contains none, and all link lead to https://docs.openvinotoolkit.org/, which is awful.

Will we see README.md again?

**Comment by asuhov** [comment]
Hi, this readme file has been moved here: https://github.com/opencv/dldt/blob/2020/build-instruction.md

**Comment by yury-gorbachev** [comment]
Can you provide a bit more information on why you think docs website is awful? Would be interested in knowing more to drive changes.
Thanks!

**Comment by banderlog** [comment]
@yury-gorbachev it is overcomplicated, hard to find\ hard to orient. I.e., I failed to find there info listed in link above.

**Comment by sorenk** [comment]
@banderlog we agree, we are working on a documentation overhaul which we plan to roll out.  We just added a much improved search capability that I should allow you to find what your looking for as a stop gap until we change the general flow and navigation.

**Comment by banderlog** [comment]
I'll look forward for it :)
