### ISSUE TITLE
Q: Fail to build with OPENBLAS (no rule to make libopenblas.so.0)

### ISSUE THREAD

**Issue by banderlog** [opencv/dldt#428]
I am trying to build dldt-2020.1 with openblas, but I am receiving next error:
```
[ 99%] Building CXX object ngraph/test/CMakeFiles/unit-test.dir/type_prop/squared_difference.cpp.o
make[2]: *** No rule to make target '/home/ubuntu/OpenBLAS-0.3.9/OUT/libopenblas.so.0', needed by '/home/ubuntu/opencv-python-inference-engine/dldt/bin/intel64/Release/lib/libMKLDNNPlugin.so'.  Stop.
make[2]: *** Waiting for unfinished jobs....
[ 99%] Building CXX object inference-engine/src/mkldnn_plugin/CMakeFiles/MKLDNNPlugin.dir/mkldnn/os/lin/lin_system_conf.cpp.o
[ 99%] Building CXX object ngraph/test/CMakeFiles/unit-test.dir/type_prop/squeeze.cpp.o
[ 99%] Building CXX object ngraph/test/CMakeFiles/unit-test.dir/type_prop/sum.cpp.o
[100%] Building CXX object ngraph/test/CMakeFiles/unit-test.dir/type_prop/reduce_prod.cpp.o
[100%] Building CXX object ngraph/test/CMakeFiles/unit-test.dir/type_prop/reduce_sum.cpp.o
[100%] Building CXX object ngraph/test/CMakeFiles/unit-test.dir/type_prop/tile.cpp.o
[100%] Building CXX object ngraph/test/CMakeFiles/unit-test.dir/type_prop/top_k.cpp.o
[100%] Building CXX object ngraph/test/CMakeFiles/unit-test.dir/type_prop/transpose.cpp.o
[100%] Building CXX object ngraph/test/CMakeFiles/unit-test.dir/type_prop/unary_elementwise.cpp.o
[100%] Building CXX object ngraph/test/CMakeFiles/unit-test.dir/type_prop/unsqueeze.cpp.o
[100%] Building CXX object ngraph/test/CMakeFiles/unit-test.dir/type_prop/variadic_split.cpp.o
[100%] Building CXX object ngraph/test/CMakeFiles/unit-test.dir/type_prop_benchmark.cpp.o
CMakeFiles/Makefile2:2426: recipe for target 'inference-engine/src/mkldnn_plugin/CMakeFiles/MKLDNNPlugin.dir/all' failed
make[1]: *** [inference-engine/src/mkldnn_plugin/CMakeFiles/MKLDNNPlugin.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[100%] Building CXX object ngraph/test/CMakeFiles/unit-test.dir/type_prop_layers.cpp.o
[100%] Building CXX object ngraph/test/CMakeFiles/unit-test.dir/util.cpp.o
[100%] Building CXX object ngraph/test/CMakeFiles/unit-test.dir/zero_dim_tensor_elimination.cpp.o
[100%] Linking CXX executable /home/ubuntu/opencv-python-inference-engine/dldt/bin/intel64/Release/unit-test
[100%] Built target unit-test
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2
```

dldt cmake:
```cmake
cmake -D CMAKE_BUILD_TYPE=Release \
    -D THREADING=TBB \
    -D ENABLE_VPU=ON \
    -D ENABLE_MYRIAD=ON \
    -D ENABLE_OPENCV=ON \
    -D ENABLE_MKL_DNN=ON \
    -D BUILD_SHARED_LIBS=OFF \
    -D BUILD_TESTS=OFF \
    -D ENABLE_PYTHON=OFF \
    -D ENABLE_TESTS=OFF \
    -D ENABLE_SAMPLES=OFF \
    -D ENABLE_GAPI_TESTS=OFF \
    -D GAPI_TEST_PERF=OFF \
    -D ENABLE_GNA=OFF \
    -D ENABLE_PROFILING_ITT=OFF \
    -D ENABLE_ALTERNATIVE_TEMP=OFF \
    -D ENABLE_SSE42=ON \
    -D ENABLE_AVX2=ON \
    -D ENABLE_AVX512F=OFF \
    -D ENABLE_NGRAPH=ON \
    -D GEMM=OPENBLAS \
    -D BLAS_INCLUDE_DIRS="/home/ubuntu/OpenBLAS-0.3.9/OUT/include/"\
    -D BLAS_LIBRARIES="/home/ubuntu/OpenBLAS-0.3.9/OUT/libopenblas.so.0" \
    -D ENABLE_CLDNN=OFF ../../dldt/
```

Openblas compiled with:
```
# compiled with 
make FC=gfortran
make install PREFIX=/home/ubuntu/OpenBLAS-0.3.9/OUT/
```

Openblas folder:
```
/home/ubuntu/OpenBLAS-0.3.9/OUT/
├── bin
├── include
│   ├── cblas.h
│   ├── f77blas.h
│   └── openblas_config.h
└── lib
    ├── cmake
    │   └── openblas
    │       ├── OpenBLASConfig.cmake
    │       └── OpenBLASConfigVersion.cmake
    ├── libopenblas.a -> libopenblas_haswellp-r0.3.9.a
    ├── libopenblas.so -> libopenblas_haswellp-r0.3.9.so
    ├── libopenblas.so.0 -> libopenblas_haswellp-r0.3.9.so
    ├── libopenblas_haswellp-r0.3.9.a
    ├── libopenblas_haswellp-r0.3.9.so
    └── pkgconfig
        └── openblas.pc
```

But it compiles with `-DBLAS_LIBRARIES=/usr/lib/x86_64-linux-gnu/libopenblasp-r0.2.20.so` and `-DBLAS_INCLUDE_DIRS=/usr/include/x86_64-linux-gnu/`

What I am doing wrong? Why dldt tries to build already compiled openblas lib?

**Comment by jgespino** [comment]
Hi @banderlog 

I was able to build dldt with OpenBLAS with the cmake command (similar to yours) below. I didn't built OpenBLAS with Fortran compiler though. Is that something you need?

I build OpenBLAS (0.3.9 dev) with:
`git clone https://github.com/xianyi/OpenBLAS.git`
`cd OpenBLAS`
`make -j 8`
`make PREFIX=/home/jesus/OpenBLAS/out/ install`

> 
    cmake -D CMAKE_BUILD_TYPE=Release \
    -D THREADING=TBB \
    -D ENABLE_VPU=ON \
    -D ENABLE_MYRIAD=ON \
    -D ENABLE_OPENCV=ON \
    -D ENABLE_MKL_DNN=ON \
    -D BUILD_SHARED_LIBS=OFF \
    -D BUILD_TESTS=OFF \
    -D ENABLE_PYTHON=OFF \
    -D ENABLE_TESTS=OFF \
    -D ENABLE_SAMPLES=OFF \
    -D ENABLE_GAPI_TESTS=OFF \
    -D GAPI_TEST_PERF=OFF \
    -D ENABLE_GNA=OFF \
    -D ENABLE_PROFILING_ITT=OFF \
    -D ENABLE_ALTERNATIVE_TEMP=OFF \
    -D ENABLE_SSE42=ON \
    -D ENABLE_AVX2=ON \
    -D ENABLE_AVX512F=OFF \
    -D ENABLE_NGRAPH=ON \
    -D GEMM=OPENBLAS \
    -D BLAS_INCLUDE_DIRS=/home/jesus/OpenBLAS/out/include \
    -D BLAS_LIBRARIES=/home/jesus/OpenBLAS/out/lib/libopenblas.so.0 \
    -D ENABLE_CLDNN=OFF \
    ..

Regards,
Jesus

**Comment by alalek** [comment]
Just a typo:

```.diff
-/home/ubuntu/OpenBLAS-0.3.9/OUT/libopenblas.so.0
+/home/ubuntu/OpenBLAS-0.3.9/OUT/lib/libopenblas.so.0
```

**Comment by banderlog** [comment]
@jgespino , thx, without `gfortran` it even smaller:

| OpenBLAS version | gfortran | blas lib size | gf libs size |
| --               | --       | --       | --           |
| 0.2.20           | +        | ~32MB    | ~2MB         |
| 0.3.9            | +        | ~13.7MB  | ~2.2MB       |
| 0.3.9            | -        | ~3.9MB   | -            |

@alalek Jeez, now I am feeling really stupid :) Thanks, now all working as it intended.

**Comment by banderlog** [comment]
@jgespino did you test inference speed with it, because I have pretty strange results:

| GEMM                   | Inference time (ms) | Lib size (MB) |
|------------------------|---------------------|---------------|
|JIT                     | 851                 | -             |
|OpenBLAS 0.2.20         | 520                 | 13.7          |
|OpenBLAS 0.3.9          | 160                 | 16.4          |
|MKL (MKL-DNN)           | 60                  | 125           |
|Openvino (mkl_tiny)     | 55                  | 30            |
|OpenBLAS 0.2.20 (binary)| 60                  | 32            |

Like old but prebuilt package is 2 times better than newest one and only 10% slower than MKL. 

https://github.com/xianyi/OpenBLAS/issues/2528
