### ISSUE TITLE
does openvino 2019 R2 support VNNI on icelake

### ISSUE THREAD

**Issue by guoyejun** [opencv/dldt#434]
I see below at https://software.intel.com/en-us/blogs/2019/04/02/improved-parallelization-extended-deep-learning-capabilities-in-intel-distribution that VNNI is already supported in R1 release. I assume that VNNI will be enabled by default when the CPU has such feature and int8 models are inferenced, no matter which hardware it is. Is it right? thanks.

New Features in 2019 R1
Supports 2nd generation Intel® Xeon® Processors (codenamed Cascade Lake) and provides performance speedup for inference through Intel® Deep Learning Boost (VNNI instruction set).

**Comment by jgespino** [comment]
Hi @guoyejun 

Thanks for reaching out, the OpenVINO toolkit added support for 10th Generation processors in the 2019 R3 release. The CPU plugin should take advantage of the new instruction set when using int8 models on 10th generation processors. 

[OpenVINO 2019 R3 Release Notes](https://software.intel.com/en-us/articles/OpenVINO-RelNotes-2019)
> Added support for 10th generation Intel® Core™ processors, which are purpose-built for accelerating AI workloads through Intel® Deep Learning Boost.

Also, we recommend using the latest OpenVINO 2020.1 release.

Regards,
Jesus

**Comment by guoyejun** [comment]
thanks.

and just another question on the optimization, how to choose the cpu-streams and nireq? I know it depends on the workload, but any direction that I can try? thanks.

My understanding is that: 
since the cpu has 8 cores, and so i'll try cpu-streams among [1,2,4,6,8], and nireq among [1,2,4,6,8], and nireq >= cpu-streams.  So there will be 5+4+3+2+1 = 15 combinations of cpu-streams and nireq. Is my coverage enough? thanks.

**Comment by jgespino** [comment]
Hi @guoyejun 

For streams, try different values from 1 to a number of CPU cores (1,2,4,8). You can find more information in the Optimization Guide, section [Throughput Mode for CPU](https://docs.openvinotoolkit.org/latest/_docs_optimization_guide_dldt_optimization_guide.html#cpu-checklist).

Hope this helps.

Regards,
Jesus

**Comment by guoyejun** [comment]
thanks.
