### ISSUE TITLE
Runtime Error: Clamp layer has incorrect number of input ports.

### ISSUE THREAD

**Issue by alinaSarwar** [opencv/dldt#444]
The following line in PyTorch:
```
      torch.clamp(boxes, min=1, max=5)
```
gets converted to the following onnx graph:

      graph(%0 : Float(2, 4)):
           %1 : Long() = onnx::Constant[value={1}]()
           %2 : Long() = onnx::Constant[value={5}]()
           %3 : Tensor = onnx::Cast[to=1](%1)
           %4 : Tensor = onnx::Cast[to=1](%2)
           %5 : Float(2, 4) = onnx::Clip(%0, %3, %4) 
       return (%5)

The onnx graph is then converted to Openvino IR. The .xml contains the following layer:
```
<layer id="3" name="5" type="Clamp" version="opset1">
	<data max="3.4028234663852886e+38" min="-3.4028234663852886e+38"/>
	<input>
		<port id="0">
			<dim>2</dim>
			<dim>4</dim>
		</port>
		<port id="1"/>
		<port id="2"/>
	</input>
	<output>
		<port id="3" precision="FP32">
		        <dim>2</dim>
			<dim>4</dim>
		</port>
	</output>
</layer>
```
Running the Inference Engine gives me the following error:

**RuntimeError: Clamp layer 5 with id: 3 has incorrect number of input ports**

Can someone help me with this?

**Comment by maxl16** [comment]
Hello @alinaSarwar 
Most likely, you might need to manually specify --input parameter for Model Optimizer while converting your model to IR file. Please find more information in Model Optimizer Frequently Asked Questions, especially items 29, 30, 31 - https://docs.openvinotoolkit.org/latest/_docs_MO_DG_prepare_model_Model_Optimizer_FAQ.html
And more on --input and --output options in this article - https://docs.openvinotoolkit.org/latest/_docs_MO_DG_prepare_model_convert_model_Cutting_Model.html

Please let us know if this works or not.

Thanks.
Best regards, Max.

**Comment by alinaSarwar** [comment]
The expected [IR notation](https://docs.openvinotoolkit.org/latest/_docs_MO_DG_prepare_model_convert_model_Legacy_IR_Layers_Catalog_Spec.html)  for clamp layer has one input only and two parameters (min and max). I manually edited the onnx clip node so that the min and max parameters were specified as attributes of the node instead of inputs. That allowed me to successfully run the Inference Engine.
