### ISSUE TITLE
Quantized model with myriad plugin

### ISSUE THREAD

**Issue by KwangSon** [opencv/dldt#449]
Thanks for great framework!

Is there any tutorial or example to execute quantized model(INT8) with myriad?
If not, any plan on it?

**Comment by maxl16** [comment]
Hello @KwangSon 
Unfortunately, VPU plugins (Myriad) currently don't support INT8 models. You can find more details about it here https://docs.openvinotoolkit.org/latest/_docs_IE_DG_supported_plugins_Supported_Devices.html#supported_model_formats
We apologize for the inconvenience. 

Best regards, Max.

**Comment by KwangSon** [comment]
@maxl16 thanks for answer.
