### ISSUE TITLE
Why does it take more time when I use two models at he same time?

### ISSUE THREAD

**Issue by jlygit** [opencv/dldt#52]
I created a InferRequest using model A, and the infer  time is 60ms,also another InferRequest using model B, and the infer  time is 43ms.
However, I created two InferRequest using Model A (called infer_a) and Model B (called infer_b) at the same time and infer the same image sequentially using infer_a, infer_b, it takes time 105ms and 264ms respectively.
Why does it take more time when I use two models?
![image](https://user-images.githubusercontent.com/10195989/49934280-e5801d80-ff08-11e8-972a-070577a2d468.png)

![image](https://user-images.githubusercontent.com/10195989/49935106-182b1580-ff0b-11e8-97b3-0ec1da8b3d5b.png)

**Comment by elvin-nnov** [comment]
I suppose you are talking about inference on CPU.
This should be a problem with oversubscriptions in inference engine based on OpenMP. There are two solutions for this issue:
1. Follow the optimization guide: https://software.intel.com/en-us/articles/OpenVINO-Inference-Engine-Optimization-Guide , section "CPU Checklist"

or

2. Recompile inference engine with TBB

**Comment by jlygit** [comment]
@elvin-nnov 
it works, thanks very much!

**Comment by jlygit** [comment]
@elvin-nnov  
hello,
How can i recompile inference engine with TBB? Is any way here?
thanks.

**Comment by emptyVoid** [comment]
It's pretty straightforward: you just add ```-DTHREADING=TBB``` to ```cmake``` arguments:
```bash
cmake -DCMAKE_BUILD_TYPE=Release -DTHREADING=TBB ..
make -j16
```
