### ISSUE TITLE
is there any documents and examples for INT8 infer of cpu plugin

### ISSUE THREAD

**Issue by liyuming1978** [opencv/dldt#61]
I find from 4.0 the int8 is supported by cpu plugin , but I don't know how ...

**Comment by elvin-nnov** [comment]
You need to follow this guide: https://docs.openvinotoolkit.org/R5/_docs_IE_DG_Int8Inference.html
Please take into account that R4 (sources of which is published here) supports inference in int8 mode only on architectures having AVX-512 extensions to x86 instruction set.

R5 efficently supports inference in int8 mode on AVX2 and SSE4.2  platforms as well. R5 can be downloaded as binary distribution of OpenVINO from https://software.intel.com/en-us/openvino-toolkit/choose-download. In addition to extendion on more platforms, R5 enables more topologies in int8 and executes more layers in low precision mode that leads to bigger performance gain.
Sources of R5 will be published later.

If you have any questions on int8 mode (please read carefully about restrictions and flow for int8 mode in R5), you can ask here.

**Comment by liyuming1978** [comment]
@elvin-nnov  thanks for you kindly help!  I will update to R5 and have a try!  that's great that support SSE4 for INT8 !

**Comment by liyuming1978** [comment]
@elvin-nnov  I find calibration_tool will compare INT8 infer result with ground-truth result?  in my mind, compare INT8 with FP32 should be enough (something like https://github.com/BUG1989/caffe-int8-convert-tools) ,  why?  the reason is that can get best accuracy?   

if ground-truth, I need download a test data with label, a little bit trouble,  and I am trying to do openpose (human pose ) from FP32 to INT8,  so I need change some code for this tool:)

**Comment by elvin-nnov** [comment]
The best approach for calibration is still open question. The same KL divergence does not guarantee that quantized model will achieve required accuracy drop. It even does not know what accuracy drop is. With any quantizatio scheme you need to download validation set and verify accuracy of quantized model vs float one.

In the same time, if you do not care a lot about optimal accuracy drop, you can try to use option "-t RawC" with passing several pictures for collect of statistic. Calibration tool will not calibrate anything, it will collect min-max statistic, that is enough for good results in int8 for some models. And definitely this will give you a performance projection when all layers are converted to int8(that is a case for approach when statistic is collected, but model is not calibrated).

But for proper calibration process, you got the idea correctly. Calibration tool needs to be extended to a) the data set for your model and 2) metric of the network accuracy. 

For OpenPose model in R4/R5, these steps should be done by you. Calibration tool is deployed in open source form even for bynary distribuition of OpenVINO, you can modify it for your needs.

**Comment by liyuming1978** [comment]
got it, thx, I will have a try, use annotation or use FP32 result as annotation.
