### ISSUE TITLE
Error when install on Ubuntu 18.04

### ISSUE THREAD

**Issue by Bahramudin** [opencv/dldt#68]
I got this error when installing and configuring OpenVINO toolkit for Linux Ubuntu 18.04.
When I got the **Model Optimizer configuration steps** and when I run
`sudo ./install_prerequisites.sh`
the output says like this:

> Hit:1 http://archive.ubuntukylin.com:10006/ubuntukylin xenial InRelease
> Ign:2 http://dl.google.com/linux/chrome/deb stable InRelease
> Hit:3 http://security.ubuntu.com/ubuntu bionic-security InRelease
> Hit:4 http://dl.google.com/linux/chrome/deb stable Release
> Hit:6 http://linux.teamviewer.com/deb stable InRelease
> Ign:7 http://ppa.launchpad.net/fcitx-team/nightly/ubuntu bionic InRelease
> Hit:8 http://cn.archive.ubuntu.com/ubuntu bionic InRelease
> Hit:9 http://cn.archive.ubuntu.com/ubuntu bionic-updates InRelease
> Ign:10 http://ppa.launchpad.net/rabbitvcs/ppa/ubuntu bionic InRelease
> Get:11 http://cn.archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
> Hit:12 http://ppa.launchpad.net/teejee2008/ppa/ubuntu bionic InRelease
> Err:13 http://ppa.launchpad.net/fcitx-team/nightly/ubuntu bionic Release
> 404 Not Found [IP: 91.189.95.83 80]
> Err:14 http://ppa.launchpad.net/rabbitvcs/ppa/ubuntu bionic Release
> 404 Not Found [IP: 91.189.95.83 80]
> Reading package lists... Done
> E: The repository 'http://ppa.launchpad.net/fcitx-team/nightly/ubuntu bionic Release' does not have a Release file.
> N: Updating from such a repository can't be done securely, and is therefore disabled by default.
> N: See apt-secure(8) manpage for repository creation and user configuration details.
> E: The repository 'http://ppa.launchpad.net/rabbitvcs/ppa/ubuntu bionic Release' does not have a Release file.
> N: Updating from such a repository can't be done securely, and is therefore disabled by default.
> N: See apt-secure(8) manpage for repository creation and user configuration details.

**And also when I run this command:**
`./demo_squeezenet_download_convert_run.sh`
this is the output:

> 
> target_precision = FP32
> 
> ###################################################
> 
> Downloading the Caffe model and the prototxt
> Installing dependencies
> Run sudo -E apt -y install build-essential python3-pip virtualenv cmake libcairo2-dev libpango1.0-dev libglib2.0-dev libgtk2.0-dev libswscale-dev libavcodec-dev libavformat-dev libgstreamer1.0-0 gstreamer1.0-plugins-base
> Hit:1 http://archive.ubuntukylin.com:10006/ubuntukylin xenial InRelease
> Ign:2 http://dl.google.com/linux/chrome/deb stable InRelease
> Hit:3 http://dl.google.com/linux/chrome/deb stable Release
> Hit:4 http://linux.teamviewer.com/deb stable InRelease
> Ign:6 http://ppa.launchpad.net/fcitx-team/nightly/ubuntu bionic InRelease
> Hit:7 http://security.ubuntu.com/ubuntu bionic-security InRelease
> Hit:8 http://cn.archive.ubuntu.com/ubuntu bionic InRelease
> Hit:9 http://cn.archive.ubuntu.com/ubuntu bionic-updates InRelease
> Ign:10 http://ppa.launchpad.net/rabbitvcs/ppa/ubuntu bionic InRelease
> Get:11 http://cn.archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
> Hit:12 http://ppa.launchpad.net/teejee2008/ppa/ubuntu bionic InRelease
> Err:13 http://ppa.launchpad.net/fcitx-team/nightly/ubuntu bionic Release
> 404 Not Found [IP: 91.189.95.83 80]
> Err:14 http://ppa.launchpad.net/rabbitvcs/ppa/ubuntu bionic Release
> 404 Not Found [IP: 91.189.95.83 80]
> Reading package lists... Done
> E: The repository 'http://ppa.launchpad.net/fcitx-team/nightly/ubuntu bionic Release' does not have a Release file.
> N: Updating from such a repository can't be done securely, and is therefore disabled by default.
> N: See apt-secure(8) manpage for repository creation and user configuration details.
> E: The repository 'http://ppa.launchpad.net/rabbitvcs/ppa/ubuntu bionic Release' does not have a Release file.
> N: Updating from such a repository can't be done securely, and is therefore disabled by default.
> N: See apt-secure(8) manpage for repository creation and user configuration details.
> Error on or near line 153; exiting with status 1

Why it shows Errors, I did everything step by step on Windows, everything goes well.

**Comment by alalek** [comment]
Invalid.

Your added custom "PPA" entries, which are not available for Ubuntu 18.04.

**Comment by Bahramudin** [comment]
@alalek Thanks! Yes, that was the problem, now it is OK. if possible, please close the issue.
