### ISSUE TITLE
Inference Engien and Model Optimizer with Python 2.7

### ISSUE THREAD

**Issue by gaoethan** [opencv/dldt#8]
Hi, I'd like to check whether there is explicit requirement to `build` and `use` IE and MO with python3.
How about building and using it with pure python 2.7 ?  Will it fail to build and use it with only python 2.7 ?

**For example:** 
_I have another application/demo which will use OpenVINO, but it only requires python 2.7 and has no python 3 support in its environment, that's to say, I have to make sure that all the python stuff in OpenVINO should be built and used with python 2.7 normally, or that demo will fail._ 

In this case,  does it work to build and use OpenVINO with only python 2.7 ? and is there any doc/guideline to help on this ? 

Thanks.

**Comment by meshaun9** [comment]
@gaoethan Python 2.7 isn't currently supported. It will fail to build with python 2.7.

**Comment by lazarevevgeny** [comment]
@gaoethan the Model Optimizer supports Python3 only and there are no plans to support Python2. Please, close the ticket if we have answered your question.
