### ISSUE TITLE
Unexpected Exception happened: No module named 'generator'

### ISSUE THREAD

**Issue by rainfld** [opencv/dldt#82]
I encountered a problem when using model-optimizer to convert the alexnet caffe model to the format which can be taken by inference-engine. 

Any suggestions are appreciated.

Command I use: 
python3.5 mo.py --framework caffe --input_model ../../open_model_zoo/model_downloader/classification/alexnet/caffe/alexnet.caffemodel

OUTPUT:
Model Optimizer arguments:
Common parameters:
        - Path to the Input Model:      /home/xxxxx/workspace/openvino_work/dldt/model-optimizer/../../open_model_zoo/model_downloader/classification/alexnet/caffe/alexnet.caffemodel
        - Path for generated IR:        /home/xxxxx/workspace/openvino_work/dldt/model-optimizer/.
        - IR output name:       alexnet
        - Log level:    ERROR
        - Batch:        Not specified, inherited from the model
        - Input layers:         Not specified, inherited from the model
        - Output layers:        Not specified, inherited from the model
        - Input shapes:         Not specified, inherited from the model
        - Mean values:  Not specified
        - Scale values:         Not specified
        - Scale factor:         Not specified
        - Precision of IR:      FP32
        - Enable fusing:        True
        - Enable grouped convolutions fusing:   True
        - Move mean values to preprocess section:       False
        - Reverse input channels:       False
Caffe specific parameters:
        - Enable resnet optimization:   True
        - Path to the Input prototxt:   /home/xxxxx/workspace/openvino_work/dldt/model-optimizer/../../open_model_zoo/model_downloader/classification/alexnet/caffe/alexnet.prototxt
        - Path to CustomLayersMapping.xml:      Default
        - Path to a mean file:  Not specified
        - Offsets for a mean file:      Not specified
Model Optimizer version:        1.5.12.49d067a0
[ ERROR ]  -------------------------------------------------
[ ERROR ]  ----------------- INTERNAL ERROR ----------------
[ ERROR ]  Unexpected exception happened.
[ ERROR ]  Please contact Model Optimizer developers and forward the following information:
[ ERROR ]  No module named 'generator'
[ ERROR ]  Traceback (most recent call last):
  File "/home/xxxxx/workspace/openvino_work/dldt/model-optimizer/mo/main.py", line 325, in main
    return driver(argv)
  File "/home/xxxxx/workspace/openvino_work/dldt/model-optimizer/mo/main.py", line 272, in driver
    import_extensions.load_dirs(argv.framework, extensions, update_registration)
  File "/home/xxxxx/workspace/openvino_work/dldt/model-optimizer/mo/utils/import_extensions.py", line 83, in load_dirs
    load_dir(framework, path, update_registration)
  File "/home/xxxxx/workspace/openvino_work/dldt/model-optimizer/mo/utils/import_extensions.py", line 64, in load_dir
    import_by_path(os.path.join(path, *p), [ext, *p])
  File "/home/xxxxx/workspace/openvino_work/dldt/model-optimizer/mo/utils/import_extensions.py", line 26, in import_by_path
    importlib.import_module('{}.{}'.format('.'.join(middle_names), name))
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/xxxxx/workspace/openvino_work/dldt/model-optimizer/mo/ops/flatten_onnx_test.py", line 20, in <module>
    from generator import generator, generate
ImportError: No module named 'generator'

[ ERROR ]  ---------------- END OF BUG REPORT --------------
[ ERROR ]  -------------------------------------------------

**Comment by SeverineH** [comment]
Install the following Python packages: coverage, m2r, pyenchant, pylint, Sphinx, safety, test-generator . In the current version, we are missing one requirement file that enables the unit tests.

**Comment by portgasray** [comment]
`python3 -m pip install coverage m2r pyenchant pylint Sphinx safety test-generator`

**Comment by schindwall** [comment]
thanks

**Comment by esmirno** [comment]
> `python3 -m pip install coverage m2r pyenchant pylint Sphinx safety test-generator`

please note that pyenchant for x64 platform cannot be easily installed, havechecked on my side that pyenchant and pylint can be skipped in order to fix issue.

**Comment by psyhtest** [comment]
In my case, only the `test-generator` was truly needed for successfully converting SSD-MobileNet for MLPerf Inference:
```
$ python3.6 -m pip show coverage m2r pyenchant pylint Sphinx safety test-generator
WARNING: Package(s) not found: Sphinx, coverage, m2r, pyenchant, pylint, safety
Name: test-generator
Version: 0.1.2
Summary: Generator is a helper for generating test methods for nose while still using unittest
Home-page: https://github.com/kevinastone/generator
Author: Kevin Stone
Author-email: kevinastone@gmail.com
License: ISCL
Location: /usr/local/lib/python3.6/dist-packages
Requires: six
Required-by:
```
