### ISSUE TITLE
DLIA source code

### ISSUE THREAD

**Issue by mustard-seed** [opencv/dldt#9]
Thanks for publishing the source code of OpenVINO! While the repository contains the sources for the CPU inference plugin libraries, I can't find anything related to FPGA. Does Intel have a timeline on publishing the RTL for the FPGA accelerators or the sources of the DLIA inference plugin?

**Comment by meshaun9** [comment]
@mustard-seed  Currently, there isn't a timeline as discussions are on-going about open source of DLA.

**Comment by moslex** [comment]
DLIA is not included into DLDT open source distribution, please read this FAQ: https://01.org/openvinooolkit/faq
