### ISSUE TITLE
Generate static libraries

### ISSUE THREAD

**Issue by ruifm** [opencv/dldt#92]
I cannot seem to find any option to build static libraries (.a) for the inference engine. Is there any cmake option that I might be missing?

Or is the only solution to manually change every instance of SHARED to STATIC in every CMakeList.txt?

**Comment by ilya-lavrenov** [comment]
why do you need static libraries?

**Comment by ruifm** [comment]
I need to generate a portable self-contained binary. Regardless of my needs, this option seems to be present when building popular libraries (such as boost, openCV, etc).

Upon further investigation, I manually changed every instance of SHARED to STATIC and managed to get the static libraries. The problem now is that when using the CPU extension plugin, it calls a shared loader class and throws this exception: [inference-engine/include/details/os/lin_shared_object_loader.h#L36](https://github.com/opencv/dldt/blob/17e66dc5a6631d630da454506902bd7c25d4170b/inference-engine/include/details/os/lin_shared_object_loader.h#L36)

This makes me wonder if the Inference Engine architecture even allows a binary to run with static libraries.

**Comment by ilya-lavrenov** [comment]
It's not possible to build OpenVINO plugins statically because they must be loaded dynamically.

**Comment by ruifm** [comment]
Is support for static linking planned for R6?

**Comment by YijinLiu** [comment]
@ruifm I wanted the same thing and played with the code a bit. With some minor changes, you could link to IE statically. See https://github.com/YijinLiu/tf-cpu/blob/master/build/build.sh#L2311 for the needed code change and https://github.com/YijinLiu/tf-cpu/blob/master/benchmark/obj_detect_dldt.cc#L139 for an example.
I only tried to do this for the mkldnn plugin though. However, it should be similar for other plugins.
