### ISSUE TITLE
wrong order of example object_detection_demo_yolov3_async

### ISSUE THREAD

**Issue by chong-lee** [opencv/dldt#95]
In the example object_detection_demo_yolov3_async,  the code do sort before filtering overlapping boxes, by default std::sort is in ascending order, but should it be descending order?
here i paste the code:
```c++
// Parsing outputs
for (auto &output : outputInfo) {
    auto output_name = output.first;
    CNNLayerPtr layer = netReader.getNetwork().getLayerByName(output_name.c_str());
    Blob::Ptr blob = async_infer_request_curr->GetBlob(output_name);
    ParseYOLOV3Output(layer, blob, resized_im_h, resized_im_w, height, width, FLAGS_t, objects);
}
// Filtering overlapping boxes
std::sort(objects.begin(), objects.end());
for (int i = 0; i < objects.size(); ++i) {
    if (objects[i].confidence == 0)
        continue;
    for (int j = i + 1; j < objects.size(); ++j)
        if (IntersectionOverUnion(objects[i], objects[j]) >= FLAGS_iou_t)
            objects[j].confidence = 0;
}
```

**Comment by shubha-ramani** [comment]
chong-lee, please clarify why you think sorting order makes a difference ?

Thanks,

Shubha

**Comment by chong-lee** [comment]
hi, Shubha. In object detection, this step should be NMS（Non-Maximum Suppression）operation. after get bounding box from network, NMS set confidence to zero for these boxes that are not part of the local maxima. In the code i paste, this only leave confidence of boxes with local minima.

**Comment by shubha-ramani** [comment]
chong-lee
The following lines of code prematurely continues the loop if confidence is 0. Even if the list were sorted in descending order, isn't this logic correct ? When I read the code, it doesn't matter which end you start from - the following code holds true. Please help me understand. 

if (objects[i].confidence == 0)
        continue;

**Comment by chong-lee** [comment]
@shubha-ramani hi, but in ascending order the following loop let bounding box of larger concidence with IOU threshold greater than FLAGS_iou_t to be 0. But i think we should set the one with smaller confidence to be 0.
```c++
for (int j = i + 1; j < objects.size(); ++j)
    if (IntersectionOverUnion(objects[i], objects[j]) >= FLAGS_iou_t)
        objects[j].confidence = 0;

**Comment by shubha-ramani** [comment]
@chong-lee OK now I see your argument. Let me check this with our developers and I will respond here.

Thanks for your patience !

Shubha

**Comment by shubha-ramani** [comment]
@chong-lee This is a confirmed bug. Thank you for finding it ! You know the workaround, so just do the sort in descending order.

Shubha
