### ISSUE TITLE
GPU plugin problem

### ISSUE THREAD

**Issue by kaynon17** [opencv/dldt#97]
Hi, when I used this engine with GPU plugin, I got an error which described as below:

 failed to create engine: No OpenCL device found which would match provided configuration:
    GeForce GTX 970: invalid vendor type

What should I do to fix this problem?

**Comment by kaynon17** [comment]
I used this engine with Intel Graphics, it works

**Comment by shubha-ramani** [comment]
Dearest kaynon 

OpenVino (made by Intel) does not support GeForce GTX 970 - which is Nvidia.

Thanks,

Shubha

**Comment by kaynon17** [comment]
Ok, I got it, Thanks
